# Generated by Codex for inventory Sprint 3.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0004_inventory_counts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorysaleapplication",
            name="applied_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_sale_applications", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="inventorysaleapplication",
            name="reversal_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="inventorysaleapplication",
            name="reversed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventorysaleapplication",
            name="reversed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_sale_reversals", to=settings.AUTH_USER_MODEL),
        ),
    ]
