# Generated by Codex for Sprint 6 inventory advanced features.
from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0005_inventory_sale_reversal_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySupplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(blank=True, default="", max_length=80)),
                ("contact_name", models.CharField(blank=True, default="", max_length=160)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("tax_id", models.CharField(blank=True, default="", max_length=80)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_suppliers_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["name", "id"], "indexes": [models.Index(fields=["name"], name="inventory_i_name_0e4ce0_idx"), models.Index(fields=["code"], name="inventory_i_code_95e515_idx"), models.Index(fields=["is_active"], name="inventory_i_is_acti_37e599_idx")]},
        ),
        migrations.AddField("InventoryItem", "supplier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_items", to="inventory.inventorysupplier")),
        migrations.AddField("InventoryItem", "unit_cost", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
        migrations.AddField("InventoryItem", "supplier_code", models.CharField(blank=True, default="", max_length=80)),
        migrations.AddField("InventoryItem", "purchase_unit", models.CharField(blank=True, default="", max_length=40)),
        migrations.AddField("InventoryItem", "purchase_to_inventory_factor", models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(choices=[("initial_stock", "Stock inicial"), ("stock_add", "Entrada"), ("stock_adjustment", "Ajuste"), ("sale_deduction", "Descuento por venta"), ("reversal", "Reversión"), ("inventory_entry", "Entrada de producto"), ("inventory_loss", "Pérdida"), ("inventory_damaged", "Producto dañado"), ("inventory_correction", "Corrección de stock"), ("inventory_count_adjustment", "Ajuste por conteo"), ("purchase_receipt", "Entrada por orden de compra")], max_length=32),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, default="", max_length=32, unique=True)),
                ("status", models.CharField(choices=[("draft", "Borrador"), ("approved", "Aprobada"), ("partially_received", "Recibida parcialmente"), ("received", "Recibida completa"), ("cancelled", "Cancelada")], default="draft", max_length=24)),
                ("payment_category", models.CharField(choices=[("cash", "Efectivo"), ("transfer", "Transferencia"), ("card", "Tarjeta"), ("credit", "Crédito"), ("other", "Otro")], default="cash", max_length=16)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("proof_reference", models.CharField(blank=True, default="", max_length=160)),
                ("proof_url", models.URLField(blank=True, default="")),
                ("subtotal", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, default="", max_length=255)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders_approved", to=settings.AUTH_USER_MODEL)),
                ("cancelled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders_cancelled", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_orders_created", to=settings.AUTH_USER_MODEL)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_orders", to="inventory.inventorysupplier")),
            ],
            options={"ordering": ["-created_at", "-id"], "indexes": [models.Index(fields=["status", "created_at"], name="inventory_p_status_70d9db_idx"), models.Index(fields=["supplier", "status"], name="inventory_p_supplie_f5ac2d_idx"), models.Index(fields=["code"], name="inventory_p_code_2d8792_idx")]},
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("quantity_ordered", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ("quantity_received", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("purchase_unit", models.CharField(blank=True, default="", max_length=40)),
                ("purchase_to_inventory_factor", models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ("inventory_quantity_ordered", models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("subtotal", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inventory_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_order_lines", to="inventory.inventoryitem")),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.purchaseorder")),
            ],
            options={"ordering": ["id"], "indexes": [models.Index(fields=["purchase_order", "inventory_item"], name="inventory_p_purcha_d2fc76_idx")]},
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(blank=True, default="", max_length=32, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="inventory.purchaseorder")),
                ("received_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_receipts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-received_at", "-id"]},
        ),
        migrations.CreateModel(
            name="PurchaseReceiptLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity_received_purchase_unit", models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)])),
                ("purchase_to_inventory_factor", models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ("quantity_added_inventory_unit", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_cost", models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("inventory_item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_receipt_lines", to="inventory.inventoryitem")),
                ("movement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="purchase_receipt_lines", to="inventory.inventorymovement")),
                ("purchase_order_line", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipt_lines", to="inventory.purchaseorderline")),
                ("receipt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="inventory.purchasereceipt")),
            ],
            options={"ordering": ["id"]},
        ),
    ]
