# Generated by Django 5.2.9 on 2026-03-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='register',
            new_name='cashier_reg_branch__34997d_idx',
            old_name='cashier_re_branch__0b897f_idx',
        ),
    ]
