# Generated by Django 5.2.11 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cashsession",
            name="unique_open_session_per_register",
        ),
        migrations.AddConstraint(
            model_name="cashsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("register",),
                name="unique_open_session_per_register_unclosed",
            ),
        ),
    ]
