# Generated by Django 5.2.9 on 2026-03-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_cashtransaction'),
        ('cashier', '0002_rename_cashier_re_branch__0b897f_idx_cashier_reg_branch__34997d_idx'),
    ]

    operations = [
    ]
