# Generated by Django 5.2.11 on 2026-03-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashier", "0003_merge_20260302_0538"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cashtransaction",
            new_name="cashier_cas_session_137cfc_idx",
            old_name="cashier_ca_session_2b6f83_idx",
        ),
        migrations.AddField(
            model_name="cashsession",
            name="closing_counted_cash",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cashsession",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="register",
            name="station_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="cashtransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("cash_out", "Cash Out"),
                    ("cash_in", "Cash In"),
                    ("expense", "Expense"),
                    ("payout", "Payout"),
                ],
                default="cash_out",
                max_length=20,
            ),
        ),
    ]
