# Generated by Django 5.2.11 on 2026-03-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cashier",
            "0004_rename_cashier_ca_session_2b6f83_idx_cashier_cas_session_137cfc_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cashsession",
            name="summary_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
