# Generated by Django 5.2.12 on 2026-04-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_replace_open_session_constraint'),
        ('cashier', '0005_cashsession_summary_snapshot'),
    ]

    operations = [
    ]
