# Generated by Django 5.2.11 on 2026-03-02 07:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "core",
            "0008_rename_core_auditlog_action_1f4a33_idx_core_auditl_action_d9fb24_idx_and_more",
        ),
        ("orders", "0011_orderinvoice_codigo_generacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo", models.TextField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "dte_numero_control",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "dte_codigo_generacion",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("dte_status", models.CharField(default="pendiente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_notes",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DTEInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pendiente", max_length=20)),
                (
                    "hacienda_state",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("motivo", models.TextField()),
                ("tipo_anulacion", models.CharField(default="total", max_length=40)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dte_invalidations",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DTEControlCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ambiente", models.CharField(default="test", max_length=20)),
                ("dte_type", models.CharField(default="CF", max_length=20)),
                ("year", models.PositiveIntegerField()),
                ("establishment_code", models.CharField(default="000", max_length=12)),
                ("pos_code", models.CharField(default="000", max_length=12)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dte_counters",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "branch",
                        "ambiente",
                        "dte_type",
                        "year",
                        "establishment_code",
                        "pos_code",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="DTERecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dte_type",
                    models.CharField(
                        choices=[
                            ("CF", "Consumidor Final"),
                            ("CCF", "Crédito Fiscal"),
                            ("NC", "Nota de Crédito"),
                            ("INVALIDATION", "Invalidación"),
                        ],
                        default="CF",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enviando", "Enviando"),
                            ("pendiente", "Pendiente"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                            ("invalidado", "Invalidado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("control_number", models.CharField(max_length=80)),
                (
                    "codigo_generacion",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "hacienda_uuid",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "sello_recepcion",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "hacienda_state",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "receiver_nit",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "receiver_name",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "issue_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("source", models.CharField(default="normal_send", max_length=40)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dte_records",
                        to="core.branch",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dte_records",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dte_type", "status"],
                        name="dte_dtereco_dte_typ_9a5585_idx",
                    ),
                    models.Index(
                        fields=["issue_date"], name="dte_dtereco_issue_d_1f7a41_idx"
                    ),
                    models.Index(
                        fields=["order", "dte_type", "status"],
                        name="dte_dtereco_order_i_8764f0_idx",
                    ),
                ],
            },
        ),
    ]
