# Generated by Django 5.2.11 on 2026-03-02 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_rename_core_auditlog_action_1f4a33_idx_core_auditl_action_d9fb24_idx_and_more",
        ),
        ("dte", "0001_initial"),
        ("orders", "0011_orderinvoice_codigo_generacion_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dterecord",
            name="dte_dtereco_order_i_8764f0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="dtecontrolcounter",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="dte_status",
        ),
        migrations.AddField(
            model_name="creditnote",
            name="request_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="response_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ENVIANDO", "Enviando"),
                    ("ACEPTADO", "Aceptado"),
                    ("RECHAZADO", "Rechazado"),
                    ("INVALIDADO", "Invalidado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dteinvalidation",
            name="dte_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invalidations",
                to="dte.dterecord",
            ),
        ),
        migrations.AddField(
            model_name="dteinvalidation",
            name="error_code",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="dteinvalidation",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dteinvalidation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ENVIANDO", "Enviando"),
                    ("ACEPTADO", "Aceptado"),
                    ("RECHAZADO", "Rechazado"),
                    ("INVALIDADO", "Invalidado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dterecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ENVIANDO", "Enviando"),
                    ("ACEPTADO", "Aceptado"),
                    ("RECHAZADO", "Rechazado"),
                    ("INVALIDADO", "Invalidado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(
                fields=["status", "created_at"], name="dte_dtereco_status_414171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(
                fields=["control_number"], name="dte_dtereco_control_161468_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(
                fields=["codigo_generacion"], name="dte_dtereco_codigo__16a370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(
                fields=["hacienda_uuid"], name="dte_dtereco_haciend_9e046b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dtecontrolcounter",
            constraint=models.UniqueConstraint(
                fields=(
                    "branch",
                    "dte_type",
                    "year",
                    "establishment_code",
                    "pos_code",
                    "ambiente",
                ),
                name="dte_counter_context_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.UniqueConstraint(
                fields=("control_number", "dte_type"),
                name="dte_record_control_type_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codigo_generacion", ""), _negated=True),
                fields=("codigo_generacion",),
                name="dte_record_codigo_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("hacienda_uuid", ""), _negated=True),
                fields=("hacienda_uuid",),
                name="dte_record_hacienda_uuid_uniq",
            ),
        ),
        migrations.RemoveField(
            model_name="dtecontrolcounter",
            name="created_at",
        ),
    ]
