# Generated by Django 5.2.11 on 2026-03-02 11:42

import os
from django.db import migrations, models


def _normalized_ambiente(raw: str | None, default_ambiente: str) -> str:
    value = (raw or "").strip().upper()
    if value in {"00", "01"}:
        return value
    if "00" in value:
        return "00"
    if "01" in value:
        return "01"
    if value in {"TEST", "CERT", "CERTIFICACION", "DEV"}:
        return "00"
    if value in {"PROD", "PRODUCCION", "PRODUCTION"}:
        return "01"
    return default_ambiente


def _table_columns(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        return {c.name for c in schema_editor.connection.introspection.get_table_description(cursor, table_name)}


def normalize_ambiente_values(apps, schema_editor):
    DTERecord = apps.get_model("dte", "DTERecord")
    DTEControlCounter = apps.get_model("dte", "DTEControlCounter")

    default_raw = os.environ.get("DTE_AMBIENTE") or os.environ.get("MH_AMBIENTE") or os.environ.get("HACIENDA_AMBIENTE")
    default_ambiente = _normalized_ambiente(default_raw, "01")

    record_cols = _table_columns(schema_editor, DTERecord._meta.db_table)
    if "ambiente" in record_cols:
        for row in DTERecord.objects.all().only("id", "ambiente"):
            normalized = _normalized_ambiente(getattr(row, "ambiente", None), default_ambiente)
            if row.ambiente != normalized:
                DTERecord.objects.filter(pk=row.pk).update(ambiente=normalized)

    counter_cols = _table_columns(schema_editor, DTEControlCounter._meta.db_table)
    if "ambiente" in counter_cols:
        for row in DTEControlCounter.objects.all().only("id", "ambiente"):
            normalized = _normalized_ambiente(getattr(row, "ambiente", None), default_ambiente)
            if row.ambiente != normalized:
                DTEControlCounter.objects.filter(pk=row.pk).update(ambiente=normalized)


def forward_map_dte_type(apps, schema_editor):
    DTERecord = apps.get_model("dte", "DTERecord")
    mapping = {
        "CF": "CF_01",
        "CCF": "CCF_03",
        "NC": "NC_05",
        "INVALIDATION": "INVALIDACION",
    }
    for old, new in mapping.items():
        DTERecord.objects.filter(dte_type=old).update(dte_type=new)


def backward_map_dte_type(apps, schema_editor):
    DTERecord = apps.get_model("dte", "DTERecord")
    mapping = {
        "CF_01": "CF",
        "CCF_03": "CCF",
        "NC_05": "NC",
        "INVALIDACION": "INVALIDATION",
    }
    for old, new in mapping.items():
        DTERecord.objects.filter(dte_type=old).update(dte_type=new)


class Migration(migrations.Migration):

    dependencies = [
        ("dte", "0002_remove_dterecord_dte_dtereco_order_i_8764f0_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dterecord",
            old_name="attempt_number",
            new_name="send_attempts",
        ),
        migrations.RunPython(normalize_ambiente_values, migrations.RunPython.noop),
        migrations.AddField(
            model_name="dterecord",
            name="ambiente",
            field=models.CharField(default="00", max_length=2),
        ),
        migrations.AlterField(
            model_name="dterecord",
            name="send_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="ambiente",
            field=models.CharField(default="00", max_length=2),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="dte_type",
            field=models.CharField(default="CF_01", max_length=20),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="establishment_code",
            field=models.CharField(default="001", max_length=3),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="pos_code",
            field=models.CharField(default="001", max_length=3),
        ),
        migrations.RunPython(forward_map_dte_type, backward_map_dte_type),
        migrations.AlterField(
            model_name="dterecord",
            name="dte_type",
            field=models.CharField(
                choices=[
                    ("CF_01", "Consumidor Final (01)"),
                    ("CCF_03", "Crédito Fiscal (03)"),
                    ("SE_14", "Sujeto Excluido (14)"),
                    ("NC_05", "Nota de Crédito (05)"),
                    ("INVALIDACION", "Invalidación"),
                ],
                default="CF_01",
                max_length=20,
            ),
        ),
    ]
