# Generated by Django 5.2.11 on 2026-03-02 11:42

from django.db import migrations, models


def forward_map_dte_type(apps, schema_editor):
    DTERecord = apps.get_model("dte", "DTERecord")
    mapping = {
        "CF": "CF_01",
        "CCF": "CCF_03",
        "NC": "NC_05",
        "INVALIDATION": "INVALIDACION",
    }
    for old, new in mapping.items():
        DTERecord.objects.filter(dte_type=old).update(dte_type=new)


def backward_map_dte_type(apps, schema_editor):
    DTERecord = apps.get_model("dte", "DTERecord")
    mapping = {
        "CF_01": "CF",
        "CCF_03": "CCF",
        "NC_05": "NC",
        "INVALIDACION": "INVALIDATION",
    }
    for old, new in mapping.items():
        DTERecord.objects.filter(dte_type=old).update(dte_type=new)


class Migration(migrations.Migration):

    dependencies = [
        ("dte", "0002_remove_dterecord_dte_dtereco_order_i_8764f0_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dterecord",
            old_name="attempt_number",
            new_name="send_attempts",
        ),
        migrations.AddField(
            model_name="dterecord",
            name="ambiente",
            field=models.CharField(default="00", max_length=2),
        ),
        migrations.AlterField(
            model_name="dterecord",
            name="send_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="ambiente",
            field=models.CharField(default="00", max_length=2),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="dte_type",
            field=models.CharField(default="CF_01", max_length=20),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="establishment_code",
            field=models.CharField(default="001", max_length=3),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="pos_code",
            field=models.CharField(default="001", max_length=3),
        ),
        migrations.RunPython(forward_map_dte_type, backward_map_dte_type),
        migrations.AlterField(
            model_name="dterecord",
            name="dte_type",
            field=models.CharField(
                choices=[
                    ("CF_01", "Consumidor Final (01)"),
                    ("CCF_03", "Crédito Fiscal (03)"),
                    ("SE_14", "Sujeto Excluido (14)"),
                    ("NC_05", "Nota de Crédito (05)"),
                    ("INVALIDACION", "Invalidación"),
                ],
                default="CF_01",
                max_length=20,
            ),
        ),
    ]
