# Generated by Django 5.2.11 on 2026-03-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_rename_core_auditlog_action_1f4a33_idx_core_auditl_action_d9fb24_idx_and_more",
        ),
        ("dte", "0003_remove_dterecord_attempt_number_dterecord_ambiente_and_more"),
        ("orders", "0011_orderinvoice_codigo_generacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="ambiente",
            field=models.CharField(
                choices=[("00", "Pruebas (00)"), ("01", "Producción (01)")],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="dterecord",
            name="ambiente",
            field=models.CharField(
                choices=[("00", "Pruebas (00)"), ("01", "Producción (01)")],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="dtecontrolcounter",
            constraint=models.CheckConstraint(
                condition=models.Q(("ambiente__in", ["00", "01"])),
                name="dte_counter_ambiente_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("ambiente__in", ["00", "01"])),
                name="dte_record_ambiente_valid",
            ),
        ),
    ]
