# Generated by Django 5.2.11 on 2026-03-02 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_rename_core_auditlog_action_1f4a33_idx_core_auditl_action_d9fb24_idx_and_more",
        ),
        ("dte", "0004_alter_dtecontrolcounter_ambiente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTEBranchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emisor_nit", models.CharField(blank=True, default="", max_length=20)),
                ("emisor_nrc", models.CharField(blank=True, default="", max_length=20)),
                (
                    "emisor_nombre",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "emisor_nombre_comercial",
                    models.CharField(blank=True, default="", max_length=180),
                ),
                (
                    "cod_actividad",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "desc_actividad",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tipo_establecimiento",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                (
                    "cod_estable_mh",
                    models.CharField(blank=True, default="X001", max_length=10),
                ),
                (
                    "cod_estable",
                    models.CharField(blank=True, default="X001", max_length=10),
                ),
                (
                    "cod_punto_venta_mh",
                    models.CharField(blank=True, default="X001", max_length=10),
                ),
                (
                    "cod_punto_venta",
                    models.CharField(blank=True, default="X001", max_length=10),
                ),
                (
                    "direccion_departamento",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "direccion_municipio",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("direccion_complemento", models.TextField(blank=True, default="")),
                ("telefono", models.CharField(blank=True, default="", max_length=20)),
                ("correo", models.EmailField(blank=True, default="", max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dte_config",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch",), name="dte_branch_config_branch_unique"
                    )
                ],
            },
        ),
    ]
