# Generated by Django 5.2.11 on 2026-03-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dte", "0006_seed_branches_and_dte_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="establishment_code",
            field=models.CharField(default="X001", max_length=4),
        ),
        migrations.AlterField(
            model_name="dtecontrolcounter",
            name="pos_code",
            field=models.CharField(default="X001", max_length=4),
        ),
    ]
