# Generated by Django 5.2.9 on 2026-03-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_seed_order_types_and_map_legacy"),
        ("dte", "0011_dterecord_mh_receipt_fields"),
        ("orders", "0015_orderitem_applied_special_price_rule"),
        ("payments", "0007_seed_payment_methods"),
    ]

    operations = [
        migrations.CreateModel(
            name="DteDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("WA", "WhatsApp")],
                        default="EMAIL",
                        max_length=10,
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("provider_status", models.IntegerField(blank=True, null=True)),
                ("provider_body", models.JSONField(blank=True, default=dict)),
                ("retries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DteInvalidationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_dte", models.CharField(default="CF_01", max_length=20)),
                ("payload_request", models.JSONField(blank=True, default=dict)),
                ("payload_response", models.TextField(blank=True, default="")),
                ("provider_status", models.IntegerField(blank=True, null=True)),
                ("provider_body", models.JSONField(blank=True, default=dict)),
                ("cf_ray", models.CharField(blank=True, default="", max_length=120)),
                ("success", models.BooleanField(default=False)),
                ("error_type", models.CharField(blank=True, default="", max_length=80)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="dterecord",
            name="dte_record_control_type_uniq",
        ),
        migrations.RenameIndex(
            model_name="dteoutbox",
            new_name="dte_dteoutb_status_25aab2_idx",
            old_name="dte_dteoutb_status_02c07a_idx",
        ),
        migrations.RenameIndex(
            model_name="dteoutbox",
            new_name="dte_dteoutb_order_i_a0a73a_idx",
            old_name="dte_dteoutb_order_i_85bcc8_idx",
        ),
        migrations.RenameIndex(
            model_name="dteoutbox",
            new_name="dte_dteoutb_last_at_3993c9_idx",
            old_name="dte_dteoutb_last_at_7bab84_idx",
        ),
        migrations.RenameIndex(
            model_name="dtetransmissionlog",
            new_name="dte_dtetran_created_4fce2f_idx",
            old_name="dte_dtetra_created_b8aeec_idx",
        ),
        migrations.RenameIndex(
            model_name="dtetransmissionlog",
            new_name="dte_dtetran_success_7d2a97_idx",
            old_name="dte_dtetra_success_60327f_idx",
        ),
        migrations.RenameIndex(
            model_name="dtetransmissionlog",
            new_name="dte_dtetran_respons_5d22ae_idx",
            old_name="dte_dtetra_respons_27d7bf_idx",
        ),
        migrations.AddField(
            model_name="creditnote",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="original_dte_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_notes",
                to="dte.dterecord",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="response_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dtecontrolcounter",
            name="anio_emision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dtecontrolcounter",
            name="est_code",
            field=models.CharField(default="M001", max_length=4),
        ),
        migrations.AddField(
            model_name="dtecontrolcounter",
            name="pv_code",
            field=models.CharField(default="P001", max_length=4),
        ),
        migrations.AddField(
            model_name="dtecontrolcounter",
            name="tipo_dte",
            field=models.CharField(default="CF_01", max_length=20),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="credit_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dte_records",
                to="dte.creditnote",
            ),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="generation_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="hacienda_processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="last_error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dte_records",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="dterecord",
            name="response_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["order", "status"], name="dte_creditn_order_i_25887c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creditnote",
            index=models.Index(
                fields=["created_at"], name="dte_creditn_created_a3ffd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(
                fields=["generation_code"], name="dte_dtereco_generat_e9b26c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(
                fields=["last_sent_at"], name="dte_dtereco_last_se_646af0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dtecontrolcounter",
            constraint=models.UniqueConstraint(
                fields=("ambiente", "tipo_dte", "anio_emision", "est_code", "pv_code"),
                name="dte_counter_segment_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("control_number", ""), _negated=True),
                fields=("control_number",),
                name="dte_record_control_uniq_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("generation_code", ""), _negated=True),
                fields=("generation_code",),
                name="dte_record_generation_uniq_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="dterecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("credit_note__isnull", True)),
                fields=("order", "dte_type"),
                name="dte_record_order_type_uniq_no_credit_note",
            ),
        ),
        migrations.AddField(
            model_name="dtedeliveryattempt",
            name="dte_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_attempts",
                to="dte.dterecord",
            ),
        ),
        migrations.AddField(
            model_name="dteinvalidationattempt",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dte_invalidation_attempts",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="dteinvalidationattempt",
            index=models.Index(fields=["order"], name="dte_dteinva_order_i_09e352_idx"),
        ),
        migrations.AddIndex(
            model_name="dteinvalidationattempt",
            index=models.Index(
                fields=["created_at"], name="dte_dteinva_created_327ca6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dteinvalidationattempt",
            index=models.Index(
                fields=["provider_status"], name="dte_dteinva_provide_42e620_idx"
            ),
        ),
    ]
