# Generated by Django 5.2.9 on 2026-03-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dte", "0012_dtedeliveryattempt_dteinvalidationattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dteoutbox",
            name="dte_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outbox_entries",
                to="dte.dterecord",
            ),
        ),
    ]
