# Generated by Django 5.2.11 on 2026-04-01

from django.db import migrations
from django.db.models import Max


def deduplicate_counter_context(apps, schema_editor):
    DTEControlCounter = apps.get_model("dte", "DTEControlCounter")

    duplicate_groups = (
        DTEControlCounter.objects.values(
            "branch_id",
            "dte_type",
            "year",
            "establishment_code",
            "pos_code",
            "ambiente",
        )
        .annotate(max_last_number=Max("last_number"), max_id=Max("id"))
    )

    for group in duplicate_groups:
        rows = list(
            DTEControlCounter.objects.filter(
                branch_id=group["branch_id"],
                dte_type=group["dte_type"],
                year=group["year"],
                establishment_code=group["establishment_code"],
                pos_code=group["pos_code"],
                ambiente=group["ambiente"],
            ).order_by("-id")
        )
        if len(rows) <= 1:
            continue
        keeper = rows[0]
        if keeper.last_number != group["max_last_number"]:
            keeper.last_number = group["max_last_number"]
            keeper.save(update_fields=["last_number", "updated_at"])
        DTEControlCounter.objects.filter(id__in=[row.id for row in rows[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dte", "0013_dteoutbox_dte_record"),
    ]

    operations = [
        migrations.RunPython(deduplicate_counter_context, migrations.RunPython.noop),
    ]
