# Generated by Django 5.2.11 on 2026-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("cashier", "Cashier"),
                    ("kitchen", "Kitchen"),
                    ("accountant", "Contador"),
                ],
                max_length=20,
            ),
        ),
    ]
