# Generated by Django 5.2.9 on 2025-12-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_branch_code_1f6f10_idx_core_branch_code_b50af7_idx_and_more'),
        ('core', '0002_taxconfig_update'),
    ]

    operations = [
    ]
