# Generated by Django 5.2.9 on 2025-12-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_taxconfig_update_0002_rename_core_branch_code_1f6f10_idx_core_branch_code_b50af7_idx_and_more'),
        ('core', '0003_merge_20251229_1822'),
    ]

    operations = [
    ]
