# Generated by Django 5.2.9 on 2025-12-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
        ('core', '0004_merge_20251229_1847'),
    ]

    operations = [
    ]
