# Generated by Django 5.2.11 on 2026-03-02 14:23

from django.db import migrations, models


def seed_default_customer(apps, schema_editor):
    Customer = apps.get_model("core", "Customer")
    customer, _ = Customer.objects.get_or_create(
        name="CONSUMIDOR FINAL",
        defaults={"is_default_consumer_final": True},
    )
    if not customer.is_default_consumer_final:
        customer.is_default_consumer_final = True
        customer.save(update_fields=["is_default_consumer_final", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0008_rename_core_auditlog_action_1f4a33_idx_core_auditl_action_d9fb24_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("tipo_documento", models.CharField(default="13", max_length=10)),
                (
                    "num_documento",
                    models.CharField(default="00000000-0", max_length=30),
                ),
                ("nrc", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "cod_actividad",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "desc_actividad",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "direccion_departamento",
                    models.CharField(default="12", max_length=2),
                ),
                ("direccion_municipio", models.CharField(default="22", max_length=2)),
                (
                    "direccion_complemento",
                    models.CharField(default="Direccion del cliente", max_length=255),
                ),
                ("telefono", models.CharField(default="00000000", max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_default_consumer_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.RunPython(seed_default_customer, migrations.RunPython.noop),
    ]
