# Generated by Django 5.2.11 on 2026-03-02 15:27

from django.db import migrations, models


def seed_consumer_final(apps, schema_editor):
    Customer = apps.get_model("core", "Customer")
    cf = (
        Customer.objects.filter(name__icontains="CONSUMIDOR", is_deleted=False).order_by("id").first()
        or Customer.objects.filter(full_name__icontains="CONSUMIDOR", is_deleted=False).order_by("id").first()
    )
    if not cf:
        cf = Customer.objects.create(
            name="CONSUMIDOR FINAL",
            full_name="CONSUMIDOR FINAL",
            client_type="CF",
            dui="00000000-0",
            telefono="00000000",
            is_deleted=False,
        )
    Customer.objects.filter(is_deleted=False).update(is_consumer_final=False)
    cf.is_consumer_final = True
    cf.save(update_fields=["is_consumer_final", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCatalog",
            fields=[
                (
                    "code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "activities_catalog",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GeoDepartment",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "geo_departments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GeoMunicipality",
            fields=[
                (
                    "code",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("department_code", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "db_table": "geo_municipalities",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="activity_code",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="activity_description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="customer",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("CF", "Consumidor Final"),
                    ("CCF", "Credito Fiscal"),
                    ("SX", "Sujeto Excluido"),
                ],
                default="CF",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="customer",
            name="department_code",
            field=models.CharField(default="12", max_length=2),
        ),
        migrations.AddField(
            model_name="customer",
            name="direccion",
            field=models.CharField(default="Direccion del cliente", max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="dui",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="full_name",
            field=models.CharField(default="", max_length=160),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_consumer_final",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="municipality_code",
            field=models.CharField(default="22", max_length=2),
        ),
        migrations.AddField(
            model_name="customer",
            name="nit",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_consumer_final", True), ("is_deleted", False)),
                fields=("is_consumer_final",),
                name="unique_active_consumer_final_customer",
            ),
        ),
        migrations.RunPython(seed_consumer_final, migrations.RunPython.noop),
    ]
