# Generated by Django 5.2.9 on 2026-03-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_activitycatalog_geodepartment_geomunicipality_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetype",
            options={"ordering": ["sort_order", "label"]},
        ),
        migrations.AddField(
            model_name="servicetype",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
