# Generated by Django 5.2.12 on 2026-04-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_cash_close_feature_flag'),
        ('core', '0013_servicetype_disposables_enabled'),
    ]

    operations = [
    ]
