# Generated by Django 5.2.9 on 2025-12-28 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_core_branch_code_1f6f10_idx_core_branch_code_b50af7_idx_and_more'),
        ('orders', '0002_rename_orders_applieddiscount_order_i_5e1b9f_idx_orders_appl_order_i_792012_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenOrderView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], default='new', max_length=20)),
                ('prep_time_minutes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_view', to='orders.order')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_orders', to='core.servicetype')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_at'], name='kitchen_kit_status_7d9140_idx')],
            },
        ),
    ]
