# Generated by Django 5.2.9 on 2025-12-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='core_branch_code_b50af7_idx',
            old_name='core_branch_code_1f6f10_idx',
        ),
        migrations.RenameIndex(
            model_name='table',
            new_name='core_table_branch__c2f253_idx',
            old_name='core_table_branch__f0c933_idx',
        ),
        migrations.RenameIndex(
            model_name='taxconfig',
            new_name='core_taxcon_branch__8079be_idx',
            old_name='core_taxconfig_branch__5d60d5_idx',
        ),
    ]
