# Generated by Django 5.2.9 on 2025-12-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applieddiscount',
            new_name='orders_appl_order_i_792012_idx',
            old_name='orders_applieddiscount_order_i_5e1b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_25e057_idx',
            old_name='orders_order_status__2272ee_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_branch__8f0bd8_idx',
            old_name='orders_order_branch__9d4d85_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_5d347b_idx',
            old_name='orders_orderitem_order_i_0dc52b_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitemmodifier',
            new_name='orders_orde_order_i_958b85_idx',
            old_name='orders_orderitemmodi_order__741a7b_idx',
        ),
    ]
