# Generated by Django 5.2.9 on 2025-12-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discounts'),
        ('orders', '0002_rename_orders_applieddiscount_order_i_5e1b9f_idx_orders_appl_order_i_792012_idx_and_more'),
    ]

    operations = [
    ]
