# Generated by Django 5.2.9 on 2025-12-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20251229_1823'),
        ('orders', '0003_order_payment_status'),
    ]

    operations = [
    ]
