# Generated by Django 5.2.9 on 2026-01-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20251230_1717'),
        ('orders', '0004_order_financial_status'),
    ]

    operations = [
    ]
