# Generated by Django 5.2.9 on 2026-01-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_waiting_payment_status'),
        ('orders', '0005_merge_20260107_0557'),
    ]

    operations = [
    ]
