# Generated by Django 5.2.9 on 2026-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_applieddiscount_breakdown'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_0e92de_idx',
            old_name='orders_order_created_at_75b490_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_service_e3b6a5_idx',
            old_name='orders_order_service_type_1a9f1b_idx',
        ),
        migrations.RenameIndex(
            model_name='orderfee',
            new_name='orders_orde_order_i_f1f8a7_idx',
            old_name='orders_orde_order_i_524afe_idx',
        ),
        migrations.AlterField(
            model_name='applieddiscount',
            name='amount_discounted',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='applieddiscount',
            name='discount_value_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
