# Generated by Django 5.2.11 on 2026-03-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0010_rename_orders_order_created_at_75b490_idx_orders_orde_created_0e92de_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderinvoice",
            name="codigo_generacion",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="dte_send_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="dte_status",
            field=models.CharField(blank=True, default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="last_dte_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="last_dte_error_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="last_dte_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderinvoice",
            name="numero_control",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
