# Generated by Django 5.2.11 on 2026-03-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_customer"),
        ("orders", "0011_orderinvoice_codigo_generacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dte_document_type",
            field=models.CharField(
                choices=[
                    ("CF", "Consumidor Final"),
                    ("CCF", "Credito Fiscal"),
                    ("SX", "Sujeto Excluido"),
                ],
                default="CF",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="iva_exempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="iva_exempt_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
