# Generated by Django 5.2.9 on 2026-03-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_customer_order_dte_document_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="assigned_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
    ]
