# Generated by Django 5.2.9 on 2026-03-06 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_servicetype_options_servicetype_sort_order"),
        ("orders", "0013_orderitem_assigned_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.servicetype",
            ),
        ),
    ]
