# Generated by Django 5.2.12 on 2026-03-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0018_productspecialpricerule"),
        ("orders", "0014_alter_order_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="applied_special_price_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="menu.productspecialpricerule",
            ),
        ),
    ]
