# Generated by Django 5.2.9 on 2025-12-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='menu_produc_categor_2de784_idx',
            old_name='menu_product_category_38490c_idx',
        ),
    ]
