# Generated by Django 5.2.9 on 2025-12-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_discount_rules'),
        ('menu', '0002_rename_menu_discount_active__c4f9aa_idx_menu_discou_active_b4fadc_idx_and_more'),
    ]

    operations = [
    ]
