# Generated by Django 5.2.9 on 2026-01-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_merge_20251229_1822'),
        ('menu', '0003_product_image_path_and_category_upper'),
    ]

    operations = [
    ]
