# Generated by Django 5.2.9 on 2026-01-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_merge_20260107_0557'),
        ('menu', '0004_product_image_charfield'),
    ]

    operations = [
    ]
