# Generated by Django 5.2.9 on 2026-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_product_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='discountruletarget',
            name='discount_rule_target_product_or_category',
        ),
        migrations.RenameIndex(
            model_name='discount',
            new_name='menu_discou_is_acti_673081_idx',
            old_name='menu_discount_is_active_2b2d8b_idx',
        ),
        migrations.AddConstraint(
            model_name='discountruletarget',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), ('category__isnull', False), _connector='OR'), name='discount_rule_target_product_or_category'),
        ),
    ]
