# Generated by Django 5.2.9 on 2026-03-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_category_options_alter_modifier_options_and_more'),
        ('menu', '0014_product_sort_order_index'),
    ]

    operations = [
    ]
