# Generated by Django 5.2.12 on 2026-03-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_seed_order_types_and_map_legacy"),
        ("menu", "0017_alter_category_image_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSpecialPriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(db_index=True, default=0)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("FIXED_PRICE", "Fixed price"),
                            ("PERCENT_OFF", "Percent off"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percent_off",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("days_of_week", models.JSONField(blank=True, default=list)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("applies_to_all_order_types", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="product_special_price_rules",
                        to="core.servicetype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_price_rules",
                        to="menu.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="menu_produc_product_ace097_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="menu_produc_priorit_2e8630_idx"
                    ),
                ],
            },
        ),
    ]
