# Generated by Codex for inventory Sprint 3 final.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0020_alter_discount_auto_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory_stock_policy",
            field=models.CharField(
                choices=[
                    ("inherit", "Heredar configuración general"),
                    ("allow", "Permitir venta aunque no haya stock"),
                    ("warn", "Advertir antes de vender"),
                    ("block", "Bloquear venta si no hay stock"),
                ],
                default="inherit",
                max_length=16,
            ),
        ),
    ]
