# Generated by Codex for inventory Sprint 3 final category policy.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0021_product_inventory_stock_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="inventory_stock_policy",
            field=models.CharField(
                choices=[
                    ("inherit", "Heredar configuración global"),
                    ("allow", "Permitir venta aunque no haya stock"),
                    ("warn", "Advertir antes de vender"),
                    ("block", "Bloquear venta si no hay stock"),
                ],
                default="inherit",
                max_length=16,
            ),
        ),
    ]
