# Generated by Codex for inventory Sprint 4.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventory_sale_reversal_tracking"),
        ("menu", "0022_category_inventory_stock_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory_components_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="track_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="tracked_inventory_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracked_products",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tracked_inventory_quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="product",
            name="auto_created_inventory_item",
            field=models.BooleanField(default=False),
        ),
    ]
