# Generated by Codex for experimental POS product image policies.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0023_product_inventory_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="pos_product_images_policy",
            field=models.CharField(
                choices=[
                    ("inherit", "Heredar configuración global"),
                    ("show", "Mostrar imágenes en productos"),
                    ("hide", "Ocultar imágenes en productos"),
                ],
                default="inherit",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pos_image_policy",
            field=models.CharField(
                choices=[
                    ("inherit", "Heredar de categoría/global"),
                    ("show", "Mostrar imagen en POS"),
                    ("hide", "Ocultar imagen en POS"),
                ],
                default="inherit",
                max_length=16,
            ),
        ),
    ]
