# Generated by Django 5.2.9 on 2026-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='printjob',
            new_name='printing_pr_type_e2c455_idx',
            old_name='printing_pr_type_4f9d5c_idx',
        ),
        migrations.RenameIndex(
            model_name='printjob',
            new_name='printing_pr_created_d60dbd_idx',
            old_name='printing_pr_created_18a3a2_idx',
        ),
        migrations.AlterField(
            model_name='printjob',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('customer', 'Customer'), ('closeout', 'Closeout'), ('refund', 'Refund'), ('void', 'Void')], max_length=20),
        ),
    ]
