# Generated by Django 5.2.9 on 2026-03-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='employees_a_employe_db3be2_idx',
            old_name='employees_at_employee_0f714c_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_e_branch__045d1b_idx',
            old_name='employees_em_branch__b6e732_idx',
        ),
        migrations.RenameIndex(
            model_name='schedule',
            new_name='employees_s_employe_ed7b9e_idx',
            old_name='employees_sc_employee_d24fbb_idx',
        ),
    ]
