from django.urls import path
from apps.orders import views, table_views
from apps.dte import views as dte_views

urlpatterns = [

    path("tables/areas/", table_views.DiningAreaListCreateView.as_view(), name="tables-areas"),
    path("tables/areas/<int:pk>/", table_views.DiningAreaDetailView.as_view(), name="tables-areas-detail"),
    path("tables/", table_views.RestaurantTableListCreateView.as_view(), name="tables-list"),
    path("tables/<int:pk>/", table_views.RestaurantTableDetailView.as_view(), name="tables-detail"),
    path("tables/layout/", table_views.TableLayoutView.as_view(), name="tables-layout"),
    path("tables/kitchen-summary/", table_views.TableKitchenSummaryView.as_view(), name="tables-kitchen-summary"),
    path("tables/ready-summary/", table_views.TableReadySummaryView.as_view(), name="tables-ready-summary"),
    path("tables/sessions/", table_views.TableSessionListCreateView.as_view(), name="tables-sessions"),
    path("tables/sessions/<int:pk>/", table_views.TableSessionDetailView.as_view(), name="tables-sessions-detail"),
    path("tables/sessions/<int:pk>/guests/<int:guest_number>/rename/", table_views.TableSessionGuestRenameView.as_view(), name="tables-sessions-guests-rename"),
    path("tables/sessions/<int:pk>/send-to-kitchen/", table_views.TableSessionSendToKitchenView.as_view(), name="tables-sessions-send-kitchen"),
    path("tables/sessions/<int:pk>/serve-ready/", table_views.TableSessionServeReadyView.as_view(), name="tables-sessions-serve-ready"),
    path("tables/sessions/<int:pk>/merge/", table_views.TableSessionMergeView.as_view(), name="tables-sessions-merge"),
    path("tables/sessions/<int:pk>/split-table/", table_views.TableSessionSplitTableView.as_view(), name="tables-sessions-split-table"),
    path("tables/sessions/<int:pk>/move-table/", table_views.TableSessionMoveTableView.as_view(), name="tables-sessions-move-table"),
    path("tables/sessions/<int:pk>/release/", table_views.TableSessionReleaseView.as_view(), name="tables-sessions-release"),
    path("tables/sessions/<int:pk>/force-release/", table_views.TableSessionForceReleaseView.as_view(), name="tables-sessions-force-release"),
    path("tables/sessions/<int:pk>/move-items/", table_views.TableSessionMoveItemsView.as_view(), name="tables-sessions-move-items"),
    path("items/<int:pk>/mark-ready/", table_views.TableOrderItemKitchenStatusView.as_view(), {"target_status": "ready"}, name="orders-items-mark-ready"),
    path("items/<int:pk>/mark-delivered/", table_views.TableOrderItemKitchenStatusView.as_view(), {"target_status": "delivered"}, name="orders-items-mark-delivered"),
    path("items/<int:pk>/serve/", table_views.TableOrderItemKitchenStatusView.as_view(), {"target_status": "delivered"}, name="orders-items-serve"),
    path("", views.OrderCreateView.as_view(), name="orders-create"),
    path("validate-price-pin/", views.ValidatePricePinView.as_view(), name="orders-validate-price-pin"),
    path("active/", views.ActiveOrderListView.as_view(), name="orders-active"),
    path("pending/", views.PendingOrderListView.as_view(), name="orders-pending"),
    path("kitchen/", views.KitchenOrderListView.as_view(), name="orders-kitchen"),
    path("<int:pk>/", views.OrderDetailView.as_view(), name="orders-detail"),
    path("<int:pk>/status/", views.OrderStatusUpdateView.as_view(), name="orders-status"),
    path("<int:pk>/send-to-kitchen/", views.OrderSendToKitchenView.as_view(), name="orders-send-to-kitchen"),
    path("<int:pk>/pending/", views.PendingOrderToggleView.as_view(), name="orders-pending-toggle"),
    path("<int:pk>/void/", views.OrderVoidView.as_view(), name="orders-void"),
    path("<int:pk>/receipt.pdf", views.OrderReceiptPDFView.as_view(), name="orders-receipt-pdf"),
    path("<int:pk>/credit-note/", dte_views.OrderCreditNoteView.as_view(), name="orders-credit-note"),
    path("<int:pk>/credit-note/preview/", dte_views.OrderCreditNotePreviewView.as_view(), name="orders-credit-note-preview"),
    path("customer-display/", views.CustomerDisplayOrderListView.as_view(), name="orders-customer-display"),
    path("customer-board/", views.CustomerBoardListView.as_view(), name="orders-customer-board"),
]
