import { useEffect, useMemo, useRef, useState } from "react";
import { PageLayout } from "@/components/layout/PageLayout";
import { ClockSV } from "@/components/ClockSV";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import {
  InventoryItem, InventoryMovement, InventoryCountSession, applyInventoryCount, cancelInventoryCount,
  createInventoryAdjustment, createInventoryCount, createInventoryItem, downloadInventoryPdf, finalizeInventoryCount,
  getInventoryCount, getInventoryCounts, getInventoryItems, getInventoryMovements, getInventoryReportAdjustments,
  getInventoryReportCounts, updateInventoryCountLines, updateInventoryItem,
} from "@/lib/api";

const UNITS = ["unidad", "docena", "media_docena", "caja_25", "caja_50", "caja_75", "caja_100", "libra", "media_libra", "onza", "kilogramo", "gramo", "litro", "mililitro", "bolsa", "paquete", "rollo", "bandeja", "botella", "lata"].map((value) => ({ value, label: value.replaceAll("_", " ").replace(/^./, (c) => c.toUpperCase()) }));
const UNIT_LABEL_BY_VALUE = Object.fromEntries(UNITS.map((unit) => [unit.value, unit.label]));
const ITEM_FILTERS = ["Todos", "Stock bajo", "Activos", "Inactivos"] as const;
const MOVEMENT_FILTERS = ["Todos", "Entradas", "Pérdidas", "Dañados", "Correcciones", "Conteos", "Ventas"] as const;
const TABS = ["Dashboard", "Ajustar", "Recontar", "Reportes"] as const;
const REPORT_TABS = ["Ajustes", "Conteos"] as const;
const ADJUSTMENT_OPTIONS = [
  { value: "entry", label: "Entrada de producto", description: "Aumenta el stock cuando ingresan productos al inventario." },
  { value: "loss", label: "Pérdida", description: "Descuenta productos perdidos del inventario." },
  { value: "damaged", label: "Producto dañado", description: "Descuenta productos que ya no pueden utilizarse o venderse." },
  { value: "correction", label: "Corrección de stock", description: "Fija el stock real después de una revisión física." },
] as const;
type AdjustmentType = typeof ADJUSTMENT_OPTIONS[number]["value"];

const MOVEMENT_LABELS: Record<string, string> = {
  initial_stock: "Stock inicial", stock_add: "Entrada de producto", stock_adjustment: "Corrección de stock", inventory_entry: "Entrada de producto",
  inventory_loss: "Pérdida", inventory_damaged: "Producto dañado", inventory_correction: "Corrección de stock", inventory_count_adjustment: "Ajuste por conteo",
  sale_deduction: "Descuento por venta", reversal: "Reversión",
};
const COUNT_STATUS_BADGE: Record<string, string> = { draft: "Borrador", in_progress: "En progreso", finalized: "Finalizado", applied: "Aplicado", cancelled: "Cancelado" };
const COUNT_TYPE_LABEL: Record<string, string> = { complete: "Conteo completo", manual: "Conteo manual", category: "Por categoría" };
const formatQuantity = (value: number | null | undefined): string => value == null || Number.isNaN(value) ? "—" : value.toLocaleString("es-SV", { maximumFractionDigits: 3 });
const isLowStock = (item: InventoryItem) => item.minStock != null && item.currentStock < item.minStock;
const parseOptionalNumber = (value: string) => (value.trim() === "" ? null : Number(value));
const dateOnly = () => new Date().toISOString().slice(0, 10);

export default function InventoryPage() {
  const [tab, setTab] = useState<(typeof TABS)[number]>("Dashboard");
  const [query, setQuery] = useState("");
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [movements, setMovements] = useState<InventoryMovement[]>([]);
  const [counts, setCounts] = useState<InventoryCountSession[]>([]);
  const [openForm, setOpenForm] = useState(false);
  const [editing, setEditing] = useState<InventoryItem | null>(null);
  const [itemFilter, setItemFilter] = useState<(typeof ITEM_FILTERS)[number]>("Todos");
  const [movementFilter, setMovementFilter] = useState<(typeof MOVEMENT_FILTERS)[number]>("Todos");
  const [openAdjustment, setOpenAdjustment] = useState(false);
  const [lockedAdjustmentItem, setLockedAdjustmentItem] = useState(false);
  const [openCountDialog, setOpenCountDialog] = useState(false);
  const [activeCount, setActiveCount] = useState<InventoryCountSession | null>(null);
  const [reportTab, setReportTab] = useState<(typeof REPORT_TABS)[number]>("Ajustes");
  const [reportAdjustments, setReportAdjustments] = useState<InventoryMovement[]>([]);
  const [reportCounts, setReportCounts] = useState<InventoryCountSession[]>([]);
  const [reportFilters, setReportFilters] = useState({ dateFrom: "", dateTo: "", inventoryItem: "", movementType: "", status: "", countType: "" });

  const [name, setName] = useState(""); const [sku, setSku] = useState(""); const [unit, setUnit] = useState("unidad"); const [stock, setStock] = useState("0"); const [minStock, setMinStock] = useState(""); const [maxStock, setMaxStock] = useState(""); const [notes, setNotes] = useState(""); const [active, setActive] = useState(true);
  const [adjustItemId, setAdjustItemId] = useState(""); const [adjustType, setAdjustType] = useState<AdjustmentType>("entry"); const [adjustQuantity, setAdjustQuantity] = useState(""); const [adjustSetStock, setAdjustSetStock] = useState(""); const [adjustReason, setAdjustReason] = useState("");
  const [countType, setCountType] = useState<"complete" | "manual">("complete"); const [countNotes, setCountNotes] = useState(""); const [selectedCountItemIds, setSelectedCountItemIds] = useState<number[]>([]); const [countDraftLines, setCountDraftLines] = useState<Record<number, { countedStock: string; note: string }>>({});
  const nameInputRef = useRef<HTMLInputElement | null>(null);

  const load = async (q = query) => {
    const [rows, logs, countRows] = await Promise.all([getInventoryItems(q), getInventoryMovements(), getInventoryCounts()]);
    setItems(rows); setMovements(logs); setCounts(countRows);
  };
  useEffect(() => { load().catch(() => toast.error("No se pudo cargar inventario")); }, []);
  useEffect(() => { if (!openForm) return; const t = window.setTimeout(() => nameInputRef.current?.focus(), 30); return () => window.clearTimeout(t); }, [openForm]);

  const resetForm = () => { setName(""); setSku(""); setUnit("unidad"); setStock(""); setMinStock(""); setMaxStock(""); setNotes(""); setActive(true); setEditing(null); };
  const openAdjustmentModal = (item?: InventoryItem) => { setAdjustItemId(item ? String(item.id) : ""); setLockedAdjustmentItem(Boolean(item)); setAdjustType("entry"); setAdjustQuantity(""); setAdjustSetStock(""); setAdjustReason(""); setOpenAdjustment(true); setTab("Ajustar"); };
  const selectedAdjustmentItem = useMemo(() => items.find((item) => String(item.id) === adjustItemId) ?? null, [adjustItemId, items]);
  const estimatedFinalStock = useMemo(() => { if (!selectedAdjustmentItem) return null; const current = selectedAdjustmentItem.currentStock; if (adjustType === "correction") return adjustSetStock.trim() === "" ? current : Number(adjustSetStock); const qty = Number(adjustQuantity || 0); return adjustType === "entry" ? current + qty : current - qty; }, [adjustQuantity, adjustSetStock, adjustType, selectedAdjustmentItem]);
  const filtered = useMemo(() => items.filter((i) => i.name.toLowerCase().includes(query.toLowerCase()) || i.sku.toLowerCase().includes(query.toLowerCase())).filter((i) => itemFilter === "Todos" || (itemFilter === "Stock bajo" && isLowStock(i)) || (itemFilter === "Activos" && i.isActive) || (itemFilter === "Inactivos" && !i.isActive)), [items, query, itemFilter]);
  const filteredMovements = useMemo(() => movements.filter((m) => { const type = m.movementType; if (movementFilter === "Todos") return true; if (movementFilter === "Entradas") return ["initial_stock", "stock_add", "inventory_entry"].includes(type); if (movementFilter === "Pérdidas") return type === "inventory_loss"; if (movementFilter === "Dañados") return type === "inventory_damaged"; if (movementFilter === "Correcciones") return ["stock_adjustment", "inventory_correction"].includes(type); if (movementFilter === "Conteos") return type === "inventory_count_adjustment"; return type === "sale_deduction"; }), [movements, movementFilter]);

  const saveAdjustment = async () => { if (!selectedAdjustmentItem) return toast.error("Selecciona un artículo."); const quantity = Number(adjustQuantity || 0); const realStock = Number(adjustSetStock || 0); if (adjustType !== "correction" && quantity <= 0) return toast.error("La cantidad debe ser mayor a 0."); if (adjustType === "correction" && (adjustSetStock.trim() === "" || realStock < 0)) return toast.error("El stock real debe ser mayor o igual a 0."); if (["loss", "damaged", "correction"].includes(adjustType) && !adjustReason.trim()) return toast.error("El motivo es obligatorio para este ajuste."); if (["loss", "damaged"].includes(adjustType) && quantity > selectedAdjustmentItem.currentStock) return toast.error("La cantidad no puede ser mayor al stock disponible."); try { await createInventoryAdjustment({ inventoryItem: selectedAdjustmentItem.id, adjustmentType: adjustType, quantity: adjustType === "correction" ? undefined : quantity, setStock: adjustType === "correction" ? realStock : undefined, reason: adjustReason }); await load(query); setOpenAdjustment(false); toast.success("Ajuste registrado correctamente."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo registrar el ajuste"); } };

  const startCount = async () => { try { const session = await createInventoryCount({ countType, notes: countNotes, itemIds: selectedCountItemIds }); setActiveCount(session); setCountDraftLines(Object.fromEntries((session.lines ?? []).map((line) => [line.id, { countedStock: line.countedStock == null ? "" : String(line.countedStock), note: line.note }]))); setOpenCountDialog(false); await load(query); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo crear el conteo"); } };
  const openCount = async (session: InventoryCountSession) => { try { const detail = await getInventoryCount(session.id); setActiveCount(detail); setCountDraftLines(Object.fromEntries((detail.lines ?? []).map((line) => [line.id, { countedStock: line.countedStock == null ? "" : String(line.countedStock), note: line.note }]))); } catch { toast.error("No se pudo abrir el conteo"); } };
  const saveCountDraft = async () => { if (!activeCount) return; const lines = (activeCount.lines ?? []).map((line) => ({ id: line.id, countedStock: countDraftLines[line.id]?.countedStock === "" ? null : Number(countDraftLines[line.id]?.countedStock ?? 0), note: countDraftLines[line.id]?.note ?? "" })); try { const updated = await updateInventoryCountLines(activeCount.id, lines); setActiveCount(updated); await load(query); toast.success("Borrador guardado"); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo guardar el conteo"); } };
  const finalizeCount = async () => { if (!activeCount) return; await saveCountDraft(); try { const updated = await finalizeInventoryCount(activeCount.id); setActiveCount(updated); await load(query); toast.success("Conteo finalizado"); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo finalizar"); } };
  const applyCount = async (session = activeCount) => { if (!session) return; if (!window.confirm("Esta acción actualizará el stock del inventario y creará movimientos de ajuste por conteo. ¿Deseas continuar?")) return; try { const result = await applyInventoryCount(session.id); setActiveCount(result.session); await load(query); toast.success("Diferencias aplicadas correctamente."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudieron aplicar diferencias"); } };
  const cancelCount = async (session: InventoryCountSession) => { if (!window.confirm("¿Cancelar este conteo? No se modificará el inventario.")) return; try { const updated = await cancelInventoryCount(session.id, "Cancelado desde inventario"); if (activeCount?.id === session.id) setActiveCount(updated); await load(query); toast.success("Conteo cancelado"); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo cancelar"); } };
  const loadReports = async () => { const filters = { dateFrom: reportFilters.dateFrom || undefined, dateTo: reportFilters.dateTo || undefined, inventoryItem: reportFilters.inventoryItem ? Number(reportFilters.inventoryItem) : undefined, movementType: reportFilters.movementType || undefined, status: reportFilters.status || undefined, countType: reportFilters.countType || undefined }; const [adjustments, countRows] = await Promise.all([getInventoryReportAdjustments(filters), getInventoryReportCounts(filters)]); setReportAdjustments(adjustments); setReportCounts(countRows); };
  useEffect(() => { loadReports().catch(() => undefined); }, []);

  const printHtml = (title: string, html: string) => { const win = window.open("", "_blank", "width=1100,height=800"); if (!win) return; win.document.write(`<html><head><title>${title}</title><style>body{font-family:sans-serif;padding:24px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:6px;font-size:12px}th{background:#166534;color:white}</style></head><body><h1>${title}</h1>${html}</body></html>`); win.document.close(); win.print(); };
  const adjustmentPdfUrl = () => { const params = new URLSearchParams(); if (reportFilters.dateFrom) params.set("date_from", reportFilters.dateFrom); if (reportFilters.dateTo) params.set("date_to", reportFilters.dateTo); if (reportFilters.inventoryItem) params.set("inventory_item", reportFilters.inventoryItem); if (reportFilters.movementType) params.set("movement_type", reportFilters.movementType); return `/inventory/reports/adjustments/pdf/${params.toString() ? `?${params.toString()}` : ""}`; };

  return (
    <PageLayout title="Inventario" subtitle="Control simple, rápido y totalmente integrado." actions={<ClockSV timeClassName="text-2xl sm:text-3xl" className="min-w-[220px]" />}>
      <div className="space-y-4">
        <div className="flex flex-wrap gap-2">{TABS.map((next) => <Button key={next} variant={tab === next ? "default" : "outline"} onClick={() => setTab(next)}>{next}</Button>)}</div>
        {tab === "Dashboard" ? <>
          <div className="mx-auto flex w-full max-w-5xl flex-col items-stretch gap-3 sm:flex-row sm:items-center"><Input placeholder="Buscar por nombre o código" value={query} onChange={(e) => setQuery(e.target.value)} className="h-12 flex-1" /><Button className="h-12 px-6" variant="outline" onClick={() => setOpenCountDialog(true)}>Recontar inventario</Button><Button className="h-12 px-6" variant="outline" onClick={() => openAdjustmentModal()}>Ajustar inventario</Button><Button className="h-12 px-6" onClick={() => { resetForm(); setOpenForm(true); }}>Nuevo artículo</Button></div>
          <div className="mx-auto flex w-full max-w-5xl flex-wrap gap-2">{ITEM_FILTERS.map((filter) => <Button key={filter} size="sm" variant={itemFilter === filter ? "default" : "outline"} onClick={() => setItemFilter(filter)}>{filter}</Button>)}</div>
          <InventoryItemsTable items={filtered} onEdit={(item) => { setEditing(item); setName(item.name); setSku(item.sku); setUnit(item.unit); setMinStock(item.minStock == null ? "" : String(item.minStock)); setMaxStock(item.maxStock == null ? "" : String(item.maxStock)); setNotes(item.notes ?? ""); setActive(item.isActive); setOpenForm(true); }} onAdjust={openAdjustmentModal} />
          <RecentMovements movements={filteredMovements} movementFilter={movementFilter} setMovementFilter={setMovementFilter} />
        </> : null}
        {tab === "Ajustar" ? <div className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold">Ajustar inventario</h3><p className="text-sm text-muted-foreground">Registra entradas, pérdidas, dañados o correcciones manuales.</p></div><Button onClick={() => openAdjustmentModal()}>Ajustar inventario</Button></div><RecentMovements movements={filteredMovements} movementFilter={movementFilter} setMovementFilter={setMovementFilter} /></div> : null}
        {tab === "Recontar" ? <div className="space-y-4"><div className="flex items-center justify-between rounded-xl border bg-card p-4"><div><h3 className="text-lg font-semibold">Recontar inventario</h3><p className="text-sm text-muted-foreground">Crea sesiones de conteo físico, guarda borradores, finaliza y aplica diferencias.</p></div><Button onClick={() => setOpenCountDialog(true)}>Nuevo conteo</Button></div><CountsTable counts={counts} onOpen={(session) => void openCount(session)} onApply={applyCount} onCancel={cancelCount} /></div> : null}
        {tab === "Reportes" ? <div className="space-y-4"><div className="flex flex-wrap gap-2">{REPORT_TABS.map((next) => <Button key={next} variant={reportTab === next ? "default" : "outline"} onClick={() => setReportTab(next)}>{next}</Button>)}</div><ReportFilters items={items} filters={reportFilters} setFilters={setReportFilters} onSearch={loadReports} reportTab={reportTab} />{reportTab === "Ajustes" ? <AdjustmentsReport rows={reportAdjustments} onPdf={() => downloadInventoryPdf(adjustmentPdfUrl(), `reporte-ajustes-inventario-${dateOnly()}.pdf`)} onPrint={() => printHtml("Reporte de Ajustes de Inventario", tableHtml(reportAdjustments.map((m) => [new Date(m.createdAt).toLocaleString(), m.inventoryItemName, MOVEMENT_LABELS[m.movementType] ?? m.movementType, formatQuantity(m.quantityChange), formatQuantity(m.quantityBefore), formatQuantity(m.quantityAfter), m.createdByUsername || "—", m.reason || "—"])))} /> : <CountsReport rows={reportCounts} onOpen={(session) => void openCount(session)} onPdf={(row) => downloadInventoryPdf(`/inventory/reports/counts/${row.id}/pdf/`, `conteo-inventario-${row.code}.pdf`)} onPrint={(row) => printHtml(`Conteo ${row.code}`, tableHtml((row.lines ?? []).map((line) => [line.inventoryItemName, line.inventoryItemSku || "—", line.inventoryItemUnit, formatQuantity(line.systemStock), formatQuantity(line.countedStock), formatQuantity(line.difference), line.note || "—"])))}/>}</div> : null}
      </div>
      <Dialog open={openForm} onOpenChange={setOpenForm}><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>{editing ? "Editar" : "Nuevo"} artículo de inventario</DialogTitle></DialogHeader><div className="grid gap-3"><Label>Código/SKU</Label><Input value={sku} onChange={(e) => setSku(e.target.value)} className="h-11" /><Label>Nombre</Label><Input ref={nameInputRef} value={name} onChange={(e) => setName(e.target.value)} className="h-11" /><Label>Unidad</Label><Select value={unit} onValueChange={setUnit}><SelectTrigger className="h-11"><SelectValue /></SelectTrigger><SelectContent>{UNITS.map((u) => <SelectItem key={u.value} value={u.value}>{u.label}</SelectItem>)}</SelectContent></Select>{!editing ? <><Label>Stock inicial</Label><Input type="number" value={stock} onChange={(e) => setStock(e.target.value)} className="h-11" /></> : null}<div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>Stock mínimo</Label><Input type="number" value={minStock} onChange={(e) => setMinStock(e.target.value)} /></div><div className="space-y-2"><Label>Stock máximo</Label><Input type="number" value={maxStock} onChange={(e) => setMaxStock(e.target.value)} /></div></div><Label>Notas</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} /><Label className="flex items-center gap-2"><input type="checkbox" checked={active} onChange={(e)=>setActive(e.target.checked)} /> Activo</Label><Button className="h-11" onClick={async () => { try { const payload = { name, sku, unit, minStock: parseOptionalNumber(minStock), maxStock: parseOptionalNumber(maxStock), notes, isActive: active }; if (editing) await updateInventoryItem(editing.id, payload); else await createInventoryItem({ ...payload, initialStock: Number(stock || 0) }); await load(query); setOpenForm(false); toast.success("Inventario guardado"); } catch { toast.error("No se pudo guardar"); } }}>Guardar</Button></div></DialogContent></Dialog>
      <Dialog open={openAdjustment} onOpenChange={setOpenAdjustment}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Ajustar inventario</DialogTitle></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Artículo</Label><Select value={adjustItemId} onValueChange={setAdjustItemId} disabled={lockedAdjustmentItem}><SelectTrigger><SelectValue placeholder="Selecciona un artículo" /></SelectTrigger><SelectContent>{items.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name} · Stock {formatQuantity(item.currentStock)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Tipo de ajuste</Label><div className="grid gap-2 sm:grid-cols-2">{ADJUSTMENT_OPTIONS.map((option) => <button key={option.value} type="button" className={cn("rounded-xl border p-3 text-left", adjustType === option.value ? "border-primary bg-primary/10" : "hover:bg-muted/40")} onClick={() => setAdjustType(option.value)}><p className="font-semibold">{option.label}</p><p className="text-xs text-muted-foreground">{option.description}</p></button>)}</div></div>{adjustType === "correction" ? <><Label>Stock real</Label><Input type="number" value={adjustSetStock} onChange={(e) => setAdjustSetStock(e.target.value)} /></> : <><Label>Cantidad</Label><Input type="number" value={adjustQuantity} onChange={(e)=>setAdjustQuantity(e.target.value)} /></>}<Label>Motivo/nota{adjustType === "entry" ? "" : " (obligatorio)"}</Label><Textarea value={adjustReason} onChange={(e)=>setAdjustReason(e.target.value)} /><div className="grid gap-2 rounded-xl border bg-muted/20 p-3 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">Stock actual</p><p className="font-semibold">{formatQuantity(selectedAdjustmentItem?.currentStock)}</p></div><div><p className="text-muted-foreground">Cambio</p><p className="font-semibold">{selectedAdjustmentItem ? formatQuantity((estimatedFinalStock ?? selectedAdjustmentItem.currentStock) - selectedAdjustmentItem.currentStock) : "—"}</p></div><div><p className="text-muted-foreground">Stock final estimado</p><p className="font-semibold">{formatQuantity(estimatedFinalStock)}</p></div></div><Button className="w-full" onClick={() => void saveAdjustment()}>Guardar ajuste</Button></div></DialogContent></Dialog>
      <Dialog open={openCountDialog} onOpenChange={setOpenCountDialog}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Recontar inventario</DialogTitle></DialogHeader><div className="space-y-4"><div className="grid gap-2 sm:grid-cols-2"><button className={cn("rounded-xl border p-3 text-left", countType === "complete" && "border-primary bg-primary/10")} onClick={() => setCountType("complete")}><p className="font-semibold">Conteo completo</p><p className="text-xs text-muted-foreground">Agrega todos los artículos activos del inventario.</p></button><button className={cn("rounded-xl border p-3 text-left", countType === "manual" && "border-primary bg-primary/10")} onClick={() => setCountType("manual")}><p className="font-semibold">Conteo manual</p><p className="text-xs text-muted-foreground">Selecciona manualmente los artículos que deseas contar.</p></button><button disabled className="rounded-xl border p-3 text-left opacity-50"><p className="font-semibold">Por categoría</p><p className="text-xs text-muted-foreground">Disponible próximamente.</p></button><button disabled className="rounded-xl border p-3 text-left opacity-50"><p className="font-semibold">Por proveedor</p><p className="text-xs text-muted-foreground">Disponible en Inventario Avanzado.</p></button></div>{countType === "manual" ? <div className="max-h-52 overflow-auto rounded-xl border p-3">{items.map((item) => <Label key={item.id} className="flex items-center gap-2 py-1"><input type="checkbox" checked={selectedCountItemIds.includes(item.id)} onChange={(e) => setSelectedCountItemIds((prev) => e.target.checked ? [...prev, item.id] : prev.filter((id) => id !== item.id))} /> {item.name} · {item.sku || "Sin código"}</Label>)}</div> : <p className="rounded-xl border p-3 text-sm text-muted-foreground">Se incluirán todos los artículos activos.</p>}<Label>Notas</Label><Textarea value={countNotes} onChange={(e) => setCountNotes(e.target.value)} /><Button onClick={() => void startCount()}>Crear conteo</Button></div></DialogContent></Dialog>
      {activeCount ? <Dialog open={Boolean(activeCount)} onOpenChange={(open) => !open && setActiveCount(null)}><DialogContent className="max-h-[90vh] max-w-6xl overflow-auto"><DialogHeader><DialogTitle>Conteo físico {activeCount.code}</DialogTitle></DialogHeader><div className="space-y-4"><CountSummary session={activeCount} /><div className="max-h-[520px] overflow-auto"><Table><TableHeader><TableRow><TableHead>Artículo</TableHead><TableHead>Código</TableHead><TableHead>Unidad</TableHead><TableHead>Stock sistema</TableHead><TableHead>Conteo físico</TableHead><TableHead>Diferencia</TableHead><TableHead>Nota</TableHead></TableRow></TableHeader><TableBody>{(activeCount.lines ?? []).map((line) => { const draft = countDraftLines[line.id] ?? { countedStock: line.countedStock == null ? "" : String(line.countedStock), note: line.note }; const diff = draft.countedStock === "" ? null : Number(draft.countedStock) - line.systemStock; const editable = ["draft", "in_progress"].includes(activeCount.status); return <TableRow key={line.id}><TableCell>{line.inventoryItemName}</TableCell><TableCell>{line.inventoryItemSku || "—"}</TableCell><TableCell>{UNIT_LABEL_BY_VALUE[line.inventoryItemUnit] ?? line.inventoryItemUnit}</TableCell><TableCell>{formatQuantity(line.systemStock)}</TableCell><TableCell>{editable ? <Input type="number" className="h-9" value={draft.countedStock} onChange={(e) => setCountDraftLines((prev) => ({ ...prev, [line.id]: { ...draft, countedStock: e.target.value } }))} /> : formatQuantity(line.countedStock)}</TableCell><TableCell className={cn(diff != null && diff > 0 && "text-emerald-500", diff != null && diff < 0 && "text-red-500")}>{diff == null ? "Pendiente" : formatQuantity(diff)}</TableCell><TableCell>{editable ? <Input className="h-9" value={draft.note} onChange={(e) => setCountDraftLines((prev) => ({ ...prev, [line.id]: { ...draft, note: e.target.value } }))} /> : line.note || "—"}</TableCell></TableRow>; })}</TableBody></Table></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void saveCountDraft()} disabled={!['draft','in_progress'].includes(activeCount.status)}>Guardar borrador</Button><Button onClick={() => void finalizeCount()} disabled={!['draft','in_progress'].includes(activeCount.status)}>Finalizar conteo</Button><Button onClick={() => void applyCount()} disabled={activeCount.status !== "finalized"}>Aplicar diferencias</Button><Button variant="destructive" onClick={() => void cancelCount(activeCount)} disabled={activeCount.status === "applied"}>Cancelar</Button><Button variant="outline" onClick={() => downloadInventoryPdf(`/inventory/reports/counts/${activeCount.id}/pdf/`, `conteo-inventario-${activeCount.code}.pdf`)}>Descargar PDF</Button></div></div></DialogContent></Dialog> : null}
    </PageLayout>
  );
}

const tableHtml = (rows: Array<Array<string | number>>) => `<table><tbody>${rows.map((row) => `<tr>${row.map((cell) => `<td>${String(cell)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
function InventoryItemsTable({ items, onEdit, onAdjust }: { items: InventoryItem[]; onEdit: (item: InventoryItem) => void; onAdjust: (item: InventoryItem) => void }) { return <div className="rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Código</TableHead><TableHead>Unidad</TableHead><TableHead>Stock</TableHead><TableHead>Mínimo</TableHead><TableHead>Máximo</TableHead><TableHead>Estado</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{items.map((item) => { const low = isLowStock(item); return <TableRow key={item.id} className={cn(low && "border-l-2 border-l-red-500/80 bg-red-500/5")}><TableCell className="font-semibold">{item.name}</TableCell><TableCell>{item.sku || "—"}</TableCell><TableCell>{UNIT_LABEL_BY_VALUE[item.unit] ?? item.unit}</TableCell><TableCell className={cn("font-semibold", low && "text-red-500")}>{formatQuantity(item.currentStock)}</TableCell><TableCell>{formatQuantity(item.minStock)}</TableCell><TableCell>{formatQuantity(item.maxStock)}</TableCell><TableCell><div className="flex flex-wrap gap-1"><Badge variant={item.isActive ? "default" : "outline"}>{item.isActive ? "Activo" : "Inactivo"}</Badge>{low ? <Badge className="bg-red-600 text-white">Stock bajo</Badge> : null}</div></TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => onEdit(item)}>Editar</Button><Button size="sm" variant="outline" onClick={() => onAdjust(item)}>Ajustar</Button></TableCell></TableRow>; })}</TableBody></Table></div>; }
function RecentMovements({ movements, movementFilter, setMovementFilter }: { movements: InventoryMovement[]; movementFilter: (typeof MOVEMENT_FILTERS)[number]; setMovementFilter: (value: (typeof MOVEMENT_FILTERS)[number]) => void }) { return <div className="rounded-xl border bg-card p-4"><div className="mb-3 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><h3 className="text-lg font-semibold">Movimientos recientes</h3><div className="flex flex-wrap gap-2">{MOVEMENT_FILTERS.map((filter) => <Button key={filter} size="sm" variant={movementFilter === filter ? "default" : "outline"} onClick={() => setMovementFilter(filter)}>{filter}</Button>)}</div></div><div className="max-h-[320px] overflow-auto"><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Producto</TableHead><TableHead>Tipo</TableHead><TableHead>Cambio</TableHead><TableHead>Antes</TableHead><TableHead>Después</TableHead><TableHead>Usuario</TableHead><TableHead>Motivo</TableHead></TableRow></TableHeader><TableBody>{movements.map((m) => <TableRow key={m.id}><TableCell>{new Date(m.createdAt).toLocaleString()}</TableCell><TableCell>{m.inventoryItemName}</TableCell><TableCell>{MOVEMENT_LABELS[m.movementType] ?? m.movementType}</TableCell><TableCell>{formatQuantity(m.quantityChange)}</TableCell><TableCell>{formatQuantity(m.quantityBefore)}</TableCell><TableCell>{formatQuantity(m.quantityAfter)}</TableCell><TableCell>{m.createdByUsername || "—"}</TableCell><TableCell>{m.reason || "—"}</TableCell></TableRow>)}</TableBody></Table></div></div>; }
function CountSummary({ session }: { session: InventoryCountSession }) { const pending = session.totalItems - session.countedItems; return <div className="grid gap-2 rounded-xl border bg-muted/20 p-3 text-sm sm:grid-cols-6"><div><p className="text-muted-foreground">Estado</p><p className="font-semibold">{COUNT_STATUS_BADGE[session.status] ?? session.status}</p></div><div><p className="text-muted-foreground">Artículos</p><p className="font-semibold">{session.totalItems}</p></div><div><p className="text-muted-foreground">Contados</p><p className="font-semibold">{session.countedItems}</p></div><div><p className="text-muted-foreground">Pendientes</p><p className="font-semibold">{pending}</p></div><div><p className="text-muted-foreground">Dif. positivas</p><p className="font-semibold text-emerald-500">{formatQuantity(session.totalPositiveDifferences)}</p></div><div><p className="text-muted-foreground">Dif. negativas</p><p className="font-semibold text-red-500">{formatQuantity(session.totalNegativeDifferences)}</p></div></div>; }
function CountsTable({ counts, onOpen, onApply, onCancel }: { counts: InventoryCountSession[]; onOpen: (s: InventoryCountSession) => void; onApply: (s: InventoryCountSession) => void; onCancel: (s: InventoryCountSession) => void }) { return <div className="rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Código/ID</TableHead><TableHead>Tipo</TableHead><TableHead>Estado</TableHead><TableHead>Usuario</TableHead><TableHead>Artículos</TableHead><TableHead>Diferencias</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{counts.map((row) => <TableRow key={row.id}><TableCell>{new Date(row.createdAt).toLocaleString()}</TableCell><TableCell>{row.code}</TableCell><TableCell>{COUNT_TYPE_LABEL[row.countType] ?? row.countType}</TableCell><TableCell><Badge>{COUNT_STATUS_BADGE[row.status] ?? row.status}</Badge></TableCell><TableCell>{row.createdByUsername || "—"}</TableCell><TableCell>{row.countedItems}/{row.totalItems}</TableCell><TableCell>{row.totalDifferences}</TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => onOpen(row)}>{["draft","in_progress"].includes(row.status) ? "Continuar" : "Ver detalle"}</Button><Button size="sm" onClick={() => onApply(row)} disabled={row.status !== "finalized"}>Aplicar</Button><Button size="sm" variant="destructive" onClick={() => onCancel(row)} disabled={row.status === "applied"}>Cancelar</Button></TableCell></TableRow>)}</TableBody></Table></div>; }
function ReportFilters({ items, filters, setFilters, onSearch, reportTab }: { items: InventoryItem[]; filters: any; setFilters: (v: any) => void; onSearch: () => void; reportTab: string }) { return <div className="grid gap-2 rounded-xl border bg-card p-3 sm:grid-cols-6"><Input type="date" value={filters.dateFrom} onChange={(e) => setFilters((p: any) => ({ ...p, dateFrom: e.target.value }))} /><Input type="date" value={filters.dateTo} onChange={(e) => setFilters((p: any) => ({ ...p, dateTo: e.target.value }))} /><Select value={filters.inventoryItem || "__all"} onValueChange={(v) => setFilters((p: any) => ({ ...p, inventoryItem: v === "__all" ? "" : v }))}><SelectTrigger><SelectValue placeholder="Artículo" /></SelectTrigger><SelectContent><SelectItem value="__all">Todos los artículos</SelectItem>{items.map((item) => <SelectItem key={item.id} value={String(item.id)}>{item.name}</SelectItem>)}</SelectContent></Select>{reportTab === "Ajustes" ? <Select value={filters.movementType || "__all"} onValueChange={(v) => setFilters((p: any) => ({ ...p, movementType: v === "__all" ? "" : v }))}><SelectTrigger><SelectValue placeholder="Tipo" /></SelectTrigger><SelectContent><SelectItem value="__all">Todos</SelectItem>{Object.entries(MOVEMENT_LABELS).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select> : <><Select value={filters.status || "__all"} onValueChange={(v) => setFilters((p: any) => ({ ...p, status: v === "__all" ? "" : v }))}><SelectTrigger><SelectValue placeholder="Estado" /></SelectTrigger><SelectContent><SelectItem value="__all">Todos</SelectItem>{Object.entries(COUNT_STATUS_BADGE).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Select value={filters.countType || "__all"} onValueChange={(v) => setFilters((p: any) => ({ ...p, countType: v === "__all" ? "" : v }))}><SelectTrigger><SelectValue placeholder="Tipo" /></SelectTrigger><SelectContent><SelectItem value="__all">Todos</SelectItem>{Object.entries(COUNT_TYPE_LABEL).map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></>}<Button onClick={onSearch}>Buscar</Button><Button variant="outline" onClick={() => { setFilters({ dateFrom: "", dateTo: "", inventoryItem: "", movementType: "", status: "", countType: "" }); setTimeout(onSearch, 0); }}>Limpiar filtros</Button></div>; }
function AdjustmentsReport({ rows, onPdf, onPrint }: { rows: InventoryMovement[]; onPdf: () => void; onPrint: () => void }) { return <div className="rounded-xl border bg-card p-4"><div className="mb-3 flex justify-between"><h3 className="text-lg font-semibold">Reporte de ajustes</h3><div className="space-x-2"><Button variant="outline" onClick={onPdf}>Descargar PDF</Button><Button variant="outline" onClick={onPrint}>Imprimir</Button></div></div><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Artículo</TableHead><TableHead>Tipo</TableHead><TableHead>Cambio</TableHead><TableHead>Stock anterior</TableHead><TableHead>Stock nuevo</TableHead><TableHead>Usuario</TableHead><TableHead>Motivo</TableHead><TableHead>Referencia</TableHead></TableRow></TableHeader><TableBody>{rows.map((m) => <TableRow key={m.id}><TableCell>{new Date(m.createdAt).toLocaleString()}</TableCell><TableCell>{m.inventoryItemName}</TableCell><TableCell>{MOVEMENT_LABELS[m.movementType] ?? m.movementType}</TableCell><TableCell>{formatQuantity(m.quantityChange)}</TableCell><TableCell>{formatQuantity(m.quantityBefore)}</TableCell><TableCell>{formatQuantity(m.quantityAfter)}</TableCell><TableCell>{m.createdByUsername || "—"}</TableCell><TableCell>{m.reason || "—"}</TableCell><TableCell>{m.referenceType ? `${m.referenceType}:${m.referenceId}` : "—"}</TableCell></TableRow>)}</TableBody></Table></div>; }
function CountsReport({ rows, onOpen, onPdf, onPrint }: { rows: InventoryCountSession[]; onOpen: (s: InventoryCountSession) => void; onPdf: (s: InventoryCountSession) => void; onPrint: (s: InventoryCountSession) => void }) { return <div className="rounded-xl border bg-card p-4"><h3 className="mb-3 text-lg font-semibold">Reporte de conteos</h3><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Código/ID</TableHead><TableHead>Tipo</TableHead><TableHead>Estado</TableHead><TableHead>Usuario</TableHead><TableHead>Artículos contados</TableHead><TableHead>Diferencias</TableHead><TableHead>Aplicado en</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.id}><TableCell>{new Date(row.createdAt).toLocaleString()}</TableCell><TableCell>{row.code}</TableCell><TableCell>{COUNT_TYPE_LABEL[row.countType] ?? row.countType}</TableCell><TableCell><Badge>{COUNT_STATUS_BADGE[row.status] ?? row.status}</Badge></TableCell><TableCell>{row.createdByUsername || "—"}</TableCell><TableCell>{row.countedItems}/{row.totalItems}</TableCell><TableCell>{row.totalDifferences}</TableCell><TableCell>{row.appliedAt ? new Date(row.appliedAt).toLocaleString() : "—"}</TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" onClick={() => onOpen(row)}>Ver detalle</Button><Button size="sm" variant="outline" onClick={() => onPdf(row)}>PDF</Button><Button size="sm" variant="outline" onClick={() => onPrint(row)}>Imprimir</Button></TableCell></TableRow>)}</TableBody></Table></div>; }
