import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Eye, Plus, Redo2, Save, Undo2 } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { createRestaurantTable, createTableArea, deleteRestaurantTable, deleteTableArea, getFeatureSettings, getTableLayout, saveTableLayout, updateRestaurantTable, updateTableArea, type DiningArea, type RestaurantTable } from "@/lib/api";

const GRID=20; const snap=(n:number)=>Math.round(n/GRID)*GRID;
const shapeLabel: Record<RestaurantTable["shape"], string> = { round:"Redonda", square:"Cuadrada", rectangle:"Rectangular", booth:"Cabina", bar:"Barra" };

export default function TablesEditor(){
  const navigate = useNavigate();
  const [enabled,setEnabled]=useState<boolean|null>(null);
  const [areas,setAreas]=useState<DiningArea[]>([]); const [tables,setTables]=useState<RestaurantTable[]>([]);
  const [mode,setMode]=useState<"tables"|"areas">("tables"); const [selectedAreaId,setSelectedAreaId]=useState<number|null>(null);
  const [selectedTableId,setSelectedTableId]=useState<number|null>(null); const [zoom,setZoom]=useState(1); const [snapOn,setSnapOn]=useState(true);
  const [dragging,setDragging]=useState<{kind:"table"|"area";id:number;dx:number;dy:number}|null>(null);
  const [pendingLayout,setPendingLayout]=useState<Record<number,{x:number;y:number;width:number;height:number;rotation:number}>>({});
  const [saveState,setSaveState]=useState<"idle"|"saving"|"saved"|"error">("idle"); const autosaveRef=useRef<number|null>(null);
  const [tableModal,setTableModal]=useState<{open:boolean;table?:RestaurantTable}>({open:false});
  const [areaModal,setAreaModal]=useState<{open:boolean;area?:DiningArea}>({open:false});
  const [tableCtx,setTableCtx]=useState<{open:boolean;x:number;y:number;id:number|null}>({open:false,x:0,y:0,id:null});
  const [areaCtx,setAreaCtx]=useState<{open:boolean;x:number;y:number;id:number|null}>({open:false,x:0,y:0,id:null});
  const [undoStack,setUndoStack]=useState<RestaurantTable[][]>([]); const [redoStack,setRedoStack]=useState<RestaurantTable[][]>([]);
  const [tableForm,setTableForm]=useState<any>({area:"",name:"",number:"1",capacity:"4",shape:"round",width:"120",height:"80",rotation:"0",color:"#10b981",isActive:true});
  const [areaForm,setAreaForm]=useState<any>({name:"",isActive:true,x:"0",y:"0",width:"320",height:"220",color:"",operational_zoom:"1",operational_offset_x:"0",operational_offset_y:"0"});

  const reload=async()=>{ const l=await getTableLayout(); setAreas(l.areas); setTables(l.tables); setSelectedAreaId((p)=>p??l.areas[0]?.id??null); };
  useEffect(()=>{ getFeatureSettings().then((s)=>setEnabled(Boolean(s.tableMapEnabled))).catch(()=>setEnabled(false)); },[]);
  useEffect(()=>{ if(enabled) void reload(); },[enabled]);

  const pushHistory=()=>{ setUndoStack((p)=>[...p.slice(-40), tables.map((t)=>({ ...t }))]); setRedoStack([]); };
  const queueAutosave=()=>{ if(autosaveRef.current) clearTimeout(autosaveRef.current); autosaveRef.current=window.setTimeout(()=>void saveNow(),450); };
  const saveNow=async()=>{ try{ setSaveState("saving"); const payload=Object.entries(pendingLayout).map(([id,v])=>({id:Number(id),...v})); if(payload.length) await saveTableLayout({tables:payload}); setPendingLayout({}); setSaveState("saved"); } catch { setSaveState("error"); toast.error("Error al guardar cambios"); } };
  const filteredTables=useMemo(()=>tables.filter((t)=>!selectedAreaId || t.area===selectedAreaId),[tables,selectedAreaId]);

  const markTable=(id:number,patch:Partial<RestaurantTable>)=>{ setTables((prev)=>prev.map((t)=>t.id===id?{...t,...patch}:t)); const base=tables.find((x)=>x.id===id); if(!base) return; setPendingLayout((p)=>({ ...p, [id]: { x:Number(patch.x??base.x), y:Number(patch.y??base.y), width:Number(patch.width??base.width), height:Number(patch.height??base.height), rotation:Number(patch.rotation??base.rotation) } })); };

  useEffect(()=>{ const h=(e:KeyboardEvent)=>{ const el=e.target as HTMLElement; if(["INPUT","TEXTAREA"].includes(el.tagName)) return; const selected=tables.find((t)=>t.id===selectedTableId); const meta=e.ctrlKey||e.metaKey;
    if(e.key==="Escape"){ setTableCtx({open:false,x:0,y:0,id:null}); setAreaCtx({open:false,x:0,y:0,id:null}); setSelectedTableId(null); }
    if((e.key==="Delete"||e.key==="Backspace")&&selected){ e.preventDefault(); void handleDeleteTable(selected); }
    if(meta&&e.key.toLowerCase()==='z'){ e.preventDefault(); const u=undoStack.at(-1); if(!u) return; setRedoStack((r)=>[...r,tables]); setTables(u); setUndoStack(undoStack.slice(0,-1)); queueAutosave(); }
    if(meta&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))){ e.preventDefault(); const r=redoStack.at(-1); if(!r) return; setUndoStack((u)=>[...u,tables]); setTables(r); setRedoStack(redoStack.slice(0,-1)); queueAutosave(); }
  }; window.addEventListener("keydown",h); return ()=>window.removeEventListener("keydown",h); });

  const handleDeleteTable=async(t:RestaurantTable)=>{ if(!confirm("¿Eliminar/desactivar esta mesa?")) return; setTables((p)=>p.filter((x)=>x.id!==t.id)); setSelectedTableId(null); try{ await deleteRestaurantTable(t.id); setSaveState("saved"); } catch (e:any){ if(String(e?.message||"").includes("404")){ toast.message("La mesa ya no existía en servidor, se quitó del mapa."); return; } toast.error("No se pudo eliminar la mesa"); await reload(); } };

  if(enabled===null) return <div className="p-6">Cargando...</div>; if(!enabled) return <div className="p-6"><Card className="p-6">Mapa de mesas no está activo.</Card></div>;

  return <div className="h-[100dvh] overflow-hidden bg-background p-2 md:p-3"><div className="grid h-full min-h-0 grid-cols-1 gap-2 lg:grid-cols-[210px_1fr]">
    <Card className="min-h-0 overflow-auto p-2">
      <div className="mb-2 flex items-center justify-between"><strong className="text-sm">Áreas</strong><Button size="icon" variant="outline" onClick={()=>{setAreaForm({name:"",isActive:true,x:"0",y:"0",width:"320",height:"220",color:"",operational_zoom:"1",operational_offset_x:"0",operational_offset_y:"0"});setAreaModal({open:true});}}><Plus className="h-4 w-4"/></Button></div>
      {areas.map((a)=><button key={a.id} className={cn("mb-1 w-full rounded border p-2 text-left text-sm",selectedAreaId===a.id&&"border-primary")} onClick={()=>setSelectedAreaId(a.id)} onContextMenu={(e)=>{e.preventDefault();setAreaCtx({open:true,x:e.clientX,y:e.clientY,id:a.id});}}>{a.name}</button>)}
    </Card>
    <div className="flex min-h-0 flex-col gap-2">
      <Card className="p-2"><div className="flex flex-wrap items-center gap-1"><Input className="h-8 w-36" placeholder="Buscar mesa"/><Button size="sm" variant={mode==='tables'?'default':'outline'} onClick={()=>setMode('tables')}>Mesas</Button><Button size="sm" variant={mode==='areas'?'default':'outline'} onClick={()=>setMode('areas')}>Áreas</Button><Button size="sm" variant="outline" onClick={()=>setTableModal({open:true})}>+ Mesa</Button><Button size="icon" variant="outline" title="Vista operativa" onClick={()=>navigate('/pos?mode=tables')}><Eye className="h-4 w-4"/></Button><Button size="icon" variant="outline" title="Guardar ahora" aria-label="Guardar ahora" onClick={()=>void saveNow()}><Save className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={()=>setZoom((z)=>Math.max(0.5,z-0.1))}>-</Button><span className="text-xs">{Math.round(zoom*100)}%</span><Button size="sm" variant="outline" onClick={()=>setZoom((z)=>Math.min(2,z+0.1))}>+</Button><Label className="ml-1 flex items-center gap-1 text-xs" title="Ajustar a cuadrícula"><Switch checked={snapOn} onCheckedChange={setSnapOn}/>Snap {snapOn?'ON':'OFF'}</Label><Button size="icon" variant="outline" disabled={!undoStack.length} title="Deshacer" aria-label="Deshacer" onClick={()=>{const u=undoStack.at(-1); if(!u) return; setRedoStack((r)=>[...r,tables]); setTables(u); setUndoStack(undoStack.slice(0,-1)); queueAutosave();}}><Undo2 className="h-4 w-4"/></Button><Button size="icon" variant="outline" disabled={!redoStack.length} title="Rehacer" aria-label="Rehacer" onClick={()=>{const r=redoStack.at(-1); if(!r) return; setUndoStack((u)=>[...u,tables]); setTables(r); setRedoStack(redoStack.slice(0,-1)); queueAutosave();}}><Redo2 className="h-4 w-4"/></Button><span className="ml-auto text-xs text-muted-foreground">{saveState==='saving'?'Guardando...':saveState==='saved'?'Guardado':saveState==='error'?'Error al guardar':'Cambios pendientes'}</span></div></Card>
      <Card className="min-h-0 flex-1 p-2">
          {mode==='tables' ? (
            <div className="h-full overflow-auto rounded border bg-slate-950" onPointerMove={(e)=>{ if(!dragging||dragging.kind!=="table") return; const nx=(e.clientX-dragging.dx)/zoom; const ny=(e.clientY-dragging.dy)/zoom; markTable(dragging.id,{x:Math.max(0,snapOn?snap(nx):nx),y:Math.max(0,snapOn?snap(ny):ny)}); }} onPointerUp={()=>{ if(dragging?.kind==='table') queueAutosave(); setDragging(null); }}>
              <div className="relative h-[1300px] w-[1900px]" style={{transform:`scale(${zoom})`,transformOrigin:'top left'}}>
                {filteredTables.map((t)=><button key={t.id} onDoubleClick={()=>{setTableForm({area:String(t.area),name:t.name,number:String(t.number),capacity:String(t.capacity),shape:t.shape,width:String(t.width),height:String(t.height),rotation:String(t.rotation),color:t.color||'#10b981',isActive:t.isActive});setTableModal({open:true,table:t});}} onContextMenu={(e)=>{e.preventDefault();setSelectedTableId(t.id);setTableCtx({open:true,x:e.clientX,y:e.clientY,id:t.id});}} onPointerDown={(e)=>{e.stopPropagation();pushHistory();setSelectedTableId(t.id);setDragging({kind:'table',id:t.id,dx:e.clientX-t.x*zoom,dy:e.clientY-t.y*zoom});}} className={cn("absolute border-2 text-white",selectedTableId===t.id&&"ring-2 ring-primary",t.shape==='round'&&'rounded-full',t.shape==='square'&&'rounded-md',t.shape==='rectangle'&&'rounded-lg',t.shape==='booth'&&'rounded-xl',t.shape==='bar'&&'rounded-sm')} style={{left:t.x,top:t.y,width:t.width,height:t.height,transform:`rotate(${t.rotation}deg)`,backgroundColor:`${t.color||'#10b981'}33`,borderColor:t.color||'#10b981'}}><div className="text-xs"><div className="font-semibold">{t.name}</div><div>Cap. {t.capacity}</div></div></button>)}
              </div>
            </div>
          ) : (
            <div className="h-full overflow-auto rounded border bg-slate-950">
              <div className="relative h-[1200px] w-[1800px]">
                {areas.map((a)=><div key={a.id} className="absolute rounded-xl border-2 p-2 text-white" style={{left:a.x,top:a.y,width:a.width,height:a.height,borderColor:a.color||'#64748b',backgroundColor:`${a.color||'#64748b'}33`}} onPointerDown={(e)=>{setDragging({kind:'area',id:a.id,dx:e.clientX-a.x*zoom,dy:e.clientY-a.y*zoom});}} onPointerMove={(e)=>{if(!dragging||dragging.kind!=='area'||dragging.id!==a.id) return; const x=Math.max(0,(e.clientX-dragging.dx)/zoom); const y=Math.max(0,(e.clientY-dragging.dy)/zoom); setAreas((p)=>p.map((x0)=>x0.id===a.id?{...x0,x,y}:x0));}} onPointerUp={async()=>{ if(dragging?.id===a.id){ const current=areas.find((x)=>x.id===a.id); if(current) await updateTableArea(a.id,{x:current.x,y:current.y}); setDragging(null); } }} onContextMenu={(e)=>{e.preventDefault();setAreaCtx({open:true,x:e.clientX,y:e.clientY,id:a.id});}} onDoubleClick={()=>{setSelectedAreaId(a.id);setMode('tables');}}><p className="font-semibold">{a.name}</p><p className="text-xs">Mesas: {tables.filter((t)=>t.area===a.id).length}</p></div>)}
              </div>
            </div>
          )}
        </Card>
    </div></div>

    <Dialog open={tableModal.open} onOpenChange={(open)=>setTableModal({open,table:tableModal.table})}><DialogContent><DialogHeader><DialogTitle>{tableModal.table?'Editar mesa':'Nueva mesa'}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-2"><div className="col-span-2"><Label>Área</Label><Select value={tableForm.area} onValueChange={(v)=>setTableForm((s:any)=>({...s,area:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{areas.map((a)=><SelectItem key={a.id} value={String(a.id)}>{a.name}</SelectItem>)}</SelectContent></Select></div><div className="col-span-2"><Label>Nombre</Label><Input value={tableForm.name} onChange={(e)=>setTableForm((s:any)=>({...s,name:e.target.value}))}/></div><div><Label>Número</Label><Input value={tableForm.number} onChange={(e)=>setTableForm((s:any)=>({...s,number:e.target.value}))}/></div><div><Label>Capacidad</Label><Input value={tableForm.capacity} onChange={(e)=>setTableForm((s:any)=>({...s,capacity:e.target.value}))}/></div><div><Label>Forma</Label><Select value={tableForm.shape} onValueChange={(v)=>setTableForm((s:any)=>({...s,shape:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(shapeLabel).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div><div><Label>Color</Label><Input type="color" value={tableForm.color} onChange={(e)=>setTableForm((s:any)=>({...s,color:e.target.value}))}/></div><div><Label>Ancho</Label><Input value={tableForm.width} onChange={(e)=>setTableForm((s:any)=>({...s,width:e.target.value}))}/></div><div><Label>Alto</Label><Input value={tableForm.height} onChange={(e)=>setTableForm((s:any)=>({...s,height:e.target.value}))}/></div><div><Label>Rotación</Label><Input value={tableForm.rotation} onChange={(e)=>setTableForm((s:any)=>({...s,rotation:e.target.value}))}/></div><div className="flex items-center justify-between"><Label>Activa</Label><Switch checked={tableForm.isActive} onCheckedChange={(v)=>setTableForm((s:any)=>({...s,isActive:v}))}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setTableModal({open:false})}>Cancelar</Button><Button onClick={async()=>{ const payload={area:Number(tableForm.area||selectedAreaId),name:tableForm.name,number:Number(tableForm.number||1),capacity:Number(tableForm.capacity||1),shape:tableForm.shape,width:Number(tableForm.width||120),height:Number(tableForm.height||80),rotation:Number(tableForm.rotation||0),color:tableForm.color,isActive:tableForm.isActive,x:tableModal.table?.x??120,y:tableModal.table?.y??120}; if(tableModal.table){ const t=await updateRestaurantTable(tableModal.table.id,payload); setTables((p)=>p.map((x)=>x.id===t.id?t:x)); } else { const created=await createRestaurantTable(payload); setTables((p)=>[...p,created]); setSelectedTableId(created.id);} setTableModal({open:false}); setSaveState('saved'); }}>Guardar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={areaModal.open} onOpenChange={(open)=>setAreaModal({open,area:areaModal.area})}><DialogContent><DialogHeader><DialogTitle>{areaModal.area?'Editar área':'Nueva área'}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-2"><div className="col-span-2"><Label>Nombre</Label><Input value={areaForm.name} onChange={(e)=>setAreaForm((s:any)=>({...s,name:e.target.value}))}/></div><div><Label>X</Label><Input value={areaForm.x} onChange={(e)=>setAreaForm((s:any)=>({...s,x:e.target.value}))}/></div><div><Label>Y</Label><Input value={areaForm.y} onChange={(e)=>setAreaForm((s:any)=>({...s,y:e.target.value}))}/></div><div><Label>Ancho</Label><Input value={areaForm.width} onChange={(e)=>setAreaForm((s:any)=>({...s,width:e.target.value}))}/></div><div><Label>Alto</Label><Input value={areaForm.height} onChange={(e)=>setAreaForm((s:any)=>({...s,height:e.target.value}))}/></div><div><Label>Color</Label><Input type="color" value={areaForm.color||'#64748b'} onChange={(e)=>setAreaForm((s:any)=>({...s,color:e.target.value}))}/></div><div><Label>Zoom operativo</Label><Input value={areaForm.operational_zoom} onChange={(e)=>setAreaForm((s:any)=>({...s,operational_zoom:e.target.value}))}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setAreaModal({open:false})}>Cancelar</Button><Button onClick={async()=>{ const payload={name:areaForm.name,isActive:areaForm.isActive,x:Number(areaForm.x||0),y:Number(areaForm.y||0),width:Number(areaForm.width||320),height:Number(areaForm.height||220),color:areaForm.color,operationalZoom:Number(areaForm.operational_zoom||1),operationalOffsetX:Number(areaForm.operational_offset_x||0),operationalOffsetY:Number(areaForm.operational_offset_y||0)}; const area=areaModal.area? await updateTableArea(areaModal.area.id,payload): await createTableArea(payload); setAreaModal({open:false}); if(areaModal.area) setAreas((p)=>p.map((x)=>x.id===area.id?area:x)); else setAreas((p)=>[...p,area]); }}>Guardar área</Button></DialogFooter></DialogContent></Dialog>

    {tableCtx.open?<div className="fixed inset-0 z-50" onClick={()=>setTableCtx({open:false,x:0,y:0,id:null})}><Card className="absolute w-56 p-2" style={{left:Math.min(tableCtx.x,window.innerWidth-240),top:Math.min(tableCtx.y,window.innerHeight-250)}} onClick={(e)=>e.stopPropagation()}>{(()=>{ const t=tables.find((x)=>x.id===tableCtx.id); if(!t) return null; return <><Button className="h-10 w-full justify-start" variant="ghost" onClick={()=>{setTableForm({area:String(t.area),name:t.name,number:String(t.number),capacity:String(t.capacity),shape:t.shape,width:String(t.width),height:String(t.height),rotation:String(t.rotation),color:t.color||'#10b981',isActive:t.isActive});setTableModal({open:true,table:t});setTableCtx({open:false,x:0,y:0,id:null});}}>Editar mesa</Button><Button className="h-10 w-full justify-start" variant="ghost" onClick={async()=>{ const created=await createRestaurantTable({...t,name:`${t.name} copia`,number:t.number+1,x:t.x+30,y:t.y+30}); setTables((p)=>[...p,created]); setSelectedTableId(created.id); setTableCtx({open:false,x:0,y:0,id:null});}}>Duplicar mesa</Button><Button className="h-10 w-full justify-start text-red-500" variant="ghost" onClick={async()=>{ await handleDeleteTable(t); setTableCtx({open:false,x:0,y:0,id:null});}}>Eliminar/desactivar</Button></>; })()}</Card></div>:null}
    {areaCtx.open?<div className="fixed inset-0 z-50" onClick={()=>setAreaCtx({open:false,x:0,y:0,id:null})}><Card className="absolute w-56 p-2" style={{left:Math.min(areaCtx.x,window.innerWidth-240),top:Math.min(areaCtx.y,window.innerHeight-250)}} onClick={(e)=>e.stopPropagation()}>{(()=>{ const a=areas.find((x)=>x.id===areaCtx.id); if(!a) return null; return <><Button className="h-10 w-full justify-start" variant="ghost" onClick={()=>{setAreaForm({name:a.name,isActive:a.isActive,x:String(a.x),y:String(a.y),width:String(a.width),height:String(a.height),color:a.color||'',operational_zoom:String(a.operationalZoom??1),operational_offset_x:String(a.operationalOffsetX??0),operational_offset_y:String(a.operationalOffsetY??0)});setAreaModal({open:true,area:a});setAreaCtx({open:false,x:0,y:0,id:null});}}>Editar área</Button><Button className="h-10 w-full justify-start" variant="ghost" onClick={()=>{setSelectedAreaId(a.id);setMode('tables');setAreaCtx({open:false,x:0,y:0,id:null});}}>Ver área</Button><Button className="h-10 w-full justify-start text-red-500" variant="ghost" onClick={async()=>{ if(confirm('¿Eliminar/desactivar esta área?')) { await deleteTableArea(a.id); await reload(); } setAreaCtx({open:false,x:0,y:0,id:null});}}>Eliminar/desactivar</Button></>; })()}</Card></div>:null}
  </div>;
}
