# Generated by Django 5.2.9 on 2025-12-28 03:47

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_core_branch_code_1f6f10_idx_core_branch_code_b50af7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('days_worked', models.PositiveIntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('late_arrivals', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('Fijo', 'Fijo'), ('Turnos rotativos', 'Turnos rotativos')], default='Fijo', max_length=40)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=list, size=None)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('allows_overtime', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee')),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch', 'status'], name='employees_e_branch__045d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'date'], name='employees_a_employe_030d17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['employee', 'schedule_type'], name='employees_s_employe_b3a0b4_idx'),
        ),
    ]
