# Generated by Django 5.2.9 on 2025-12-28 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_core_branch_code_1f6f10_idx_core_branch_code_b50af7_idx_and_more'),
        ('orders', '0002_rename_orders_applieddiscount_order_i_5e1b9f_idx_orders_appl_order_i_792012_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=40)),
                ('payment_method', models.CharField(max_length=40)),
                ('items', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashier_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('completado', 'Completado'), ('anulado', 'Anulado'), ('reembolsado', 'Reembolsado')], default='completado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_snapshots', to='core.branch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_snapshots', to='orders.order')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_snapshots', to='core.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'status'], name='reports_sal_created_3dd899_idx'), models.Index(fields=['branch', 'created_at'], name='reports_sal_branch__c223e1_idx')],
            },
        ),
    ]
