# Generated by Django 5.2.9 on 2026-03-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_cash_received'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_order_i_4d9364_idx',
            old_name='payments_payment_order_c54b13_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_method_70cfb8_idx',
            old_name='payments_payment_method_4c0d39_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='payments_re_order_i_c6557f_idx',
            old_name='payments_re_order_i_0d10d8_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='payments_re_method_e77ff9_idx',
            old_name='payments_re_method_4b0468_idx',
        ),
    ]
