# Generated by Django 5.2.11 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_seed_payment_methods"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_type",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
